### ISSUE TITLE
[Reveal] Focus Ring Bug

### ISSUE THREAD

**Issue by IamManchanda** [zurb/foundation-sites#10028]
Using Ubuntu - Getting Blue line on focus 

https://codepen.io/IamManchanda/pen/vmrQwL?editors=1000

**User agent stylesheet**
```scss
:focus {
    outline: -webkit-focus-ring-color auto 5px;
}
```

![blue-line-focus](https://cloud.githubusercontent.com/assets/4970624/26072960/f9a2bce6-39ca-11e7-8df3-f83a4dc0a63c.png)
