### ISSUE TITLE
[Docs] Make docs WebP First  

### ISSUE THREAD

**Issue by IamManchanda** [zurb/foundation-sites#10547]
This is based as per the discussion with @kball 

For regular images ( `img` tag ) ... Simple [onerror](https://developer.mozilla.org/en/docs/Web/API/GlobalEventHandlers/onerror) Event

```html
<img src="image.webp" onerror="this.onerror=null; this.src='image.png'">
```

------

For Background images, we can trigger as discussed in this article 
https://davidwalsh.name/detect-webp

```js
const body = document.querySelector('body');

async function supportsWebp() {
  if (!self.createImageBitmap) return false;
  const webpData = 'data:image/webp;base64,UklGRh4AAABXRUJQVlA4TBEAAAAvAAAAAAfQ//73v/+BiOh/AAA=';
  const blob = await fetch(webpData).then(r => r.blob());
  return createImageBitmap(blob).then(() => true, () => false);
}

(async () => {
  if(await supportsWebp()) {
     body.classname = 'webp';
  }
  else {
     body.classname = 'no-webp';
  }
})();
```

and then we can just 

```scss
.no-webp .element {
  background-image: url("image.jpg");
}

.webp .element {
  background-image: url("image.webp");
}
```
