### ISSUE TITLE
Wrong CSS :hover rules on production build using webpack

### ISSUE THREAD

**Issue by jlambe** [zurb/foundation-sites#10605]
We have built a website using the latest Foundation framework. We use the NPM version for installation and manage our dependencies using Yarn.

We have a `yarn watch` command for development which compiles everything correctly, from sass to css and the Orbit and Offcanvas plugins to correct plugins. Everything using ES6 syntax and Js modules.

The issue is now on compilation for "production". We have a `yarn build` command that sets the NODE_ENV variable to `production` and we compile everything. The Js is compiled and minified correctly (by using the babel-minify plugin) but the css is just broken (sort of).

When we inspect the compiled CSS, for unknown reasons, it creates a `:hover, :focus` general rule with a background and text colors. Meaning that when we hover over any elements we have white rectangles:

```css
:hover, :focus {
    border-color: gray;
    color: gray;
}

:hover, :focus {
    background-color: #fff;
    color: #000;
}
```

#### How to reproduce this bug:

1. Setup the foundation framework with WebPack 2 or 3.
2. Set a "development" and a "production" environment.
3. Run a `production` compilation.

#### What should happen:

Correct CSS rules.

#### What happened instead:

Generates a generic `:hover, :focus` rule like so:

```css
:hover, :focus {
    border-color: gray;
    color: gray;
}

:hover, :focus {
    background-color: #fff;
    color: #000;
}
```

#### Browser(s) and Device(s) tested on:

Chrome, Safari, Firefox but should be the same for all based on above rule.

#### Foundation Version(s) you are using:

Based on our yarn.lock, the version 6.4.3
