### ISSUE TITLE
[Feature Queries] CSS Grid and Progressive Enhancement | 2018

### ISSUE THREAD

**Issue by IamManchanda** [zurb/foundation-sites#10661]
**Inspiration:** https://codepen.io/primalivet/pen/ryjKmV?editors=0100

This Thread is a successor of #10134, just to attract more viewership needed!

Well, Things have changed a lot now!

Microsoft is also now supporting CSS Grid!
https://twitter.com/MSEdgeDev/status/908096400507858944
Again, Thanks to @gregwhitworth and Microsoft Team!

----

http://caniuse.com/#feat=css-featurequeries
Freaking **92% global** ... even Opera Mini/UC Browser is supported
Atleast expect it to go to 95-97 by 2018? No? 

IE (11) Support is going down day by day, its **3% right now**, expect it to go 2% or even 1% in 2018
Update: We may be supporting IE 10 and 11 also most probably! Working on it!

So here What I propose for Foundation 7 and all of it without dirty hacks:

```css
/**
 * IE 6-10 Browser support = around 0%
 * IE 11 Browser Support = 3% (Going down)
 * But Still we will support IE
 */

@supports (display: grid) {
  .grid-x, .grid-y {
    /* CSS Grid */
    /* Both 1D and 2D */
    display: grid;  /* Latest Chrome, Firefox, Safari, Opera, Edge */
  }
}
@supports not (display: grid) {
  @supports (display: flex) {
    /* Flex Grid, Full fallback support for 1D without any code bloat. */
    /* Progressive Enhancement for 2D */
    .grid-x, .grid-y {
      display: flex;  /* Old Chrome, Firefox, Safari, Opera, Edge, Opera Mini */
    }
  }
  @supports not (display: flex) {
    /* Progressive Enhancement only! */
    .grid-x, .grid-y {
      display: inline-block; /* UC Browser */
    }
  }
}

/* Hack for IE, assuming that IE is a browser */
/* Sass Customisation to rip this duplicate code if you DONT want to support IE */
@media screen and (-ms-high-contrast: active), screen and (-ms-high-contrast: none) {
  .grid-x, .grid-y {
    display: flex;  /* IE 10, 11 */
  }
}
```
