### ISSUE TITLE
stacked button groups are always expanded

### ISSUE THREAD

**Issue by fvanderwielen** [zurb/foundation-sites#10693]
#### How to reproduce this bug:

given a button group with 2 buttons, to stack on medium down breakpoints but are not expanded:
```HTML
<div class="button-group stacked-for-medium">
    <button type="button" class="button">button1</button>
    <button type="button" class="button">button2</button>
</div>
```
when I view this on a wider than medium breakpoint
then I expect the buttons to not use full width available to them and size normally, as they are not `.expanded`.

In other words, I would expect the following CSS:
```CSS
@media print, screen and (min-width: 64em) {
  .button-group.stacked-for-medium .button {
	flex: 0 0 auto;
	margin-bottom: 0;
  }
}

@media print, screen and (min-width: 64em) {
  .button-group.stacked-for-medium.expanded .button {
	flex: 1 1 auto;
	margin-bottom: 0;
  }
}
```
The above 

see also : https://codepen.io/ZURBFoundation/pen/bWMemL?editors=1000
related issue: https://github.com/zurb/foundation-sites/issues/7393

#### What should happen:
button group does not take full width

#### What happened instead:
button group does take full width, as if it were expanded

#### Browser(s) and Device(s) tested on:
Firefox 55.0.3 (32-bit)

#### Foundation Version(s) you are using:
 * Foundation for Sites by ZURB
 * Version 6.4.3

#### Test case link:
https://codepen.io/ZURBFoundation/pen/bWMemL?editors=1000

- [CodePen with Foundation 6.3.1, Float Grid and MotionUI](http://codepen.io/IamManchanda/pen/LWGZxR)
- [CodePen with Foundation 6.3.1, Float Grid with RTL Direction and MotionUI](http://codepen.io/IamManchanda/pen/bRYOMv)
- [CodePen with Foundation 6.3.1, Flexbox grid and MotionUI](http://codepen.io/IamManchanda/pen/zZrBEv)

- [CodePen with Foundation 6.4.1, XY Flexbox grid and MotionUI](http://codepen.io/IamManchanda/pen/EXbGKJ)
- [CodePen with Foundation 6.4.1, XY Flexbox grid with RTL Direction and MotionUI](http://codepen.io/IamManchanda/pen/qjVLoO)
- [CodePen with Foundation 6.4.1, XY Flexbox grid with Prototype Mode and MotionUI](http://codepen.io/IamManchanda/pen/XgzopG)
- [CodePen with Foundation 6.4.1, Float Grid and MotionUI](http://codepen.io/IamManchanda/pen/qjVLrB)
