### ISSUE TITLE
[Regression] Setting $menu-item-background-hover no longer works

### ISSUE THREAD

**Issue by glen-84** [zurb/foundation-sites#10758]
When upgrading from 6.3.1 to 6.4.3, the background of hovered menu items no longer changes.

Workaround:

```scss
.menu-hover > li:hover {
    background-color: $menu-item-background-hover;
}
```
