### ISSUE TITLE
Responsive gutters for xy-cell() doesn't work as expected.

### ISSUE THREAD

**Issue by Lazerproof** [zurb/foundation-sites#10818]
My settings:
```
$breakpoints: (
  small: 0,
  medium: 640px,
  large: 1024px,
  xlarge: 1200px,
  xxlarge: 1440px,
);
$print-breakpoint: large;
$breakpoint-classes: (small medium large);
```
```
$xy-grid: true;
$grid-container: $global-width;
$grid-columns: 12;
$grid-margin-gutters: (
  small: 20px,
  medium: 30px,
);
$grid-padding-gutters: $grid-margin-gutters;
$grid-container-padding: $grid-padding-gutters;
$grid-container-max: $global-width;
$xy-block-grid-max: 8;
```

This code
```
@include xy-cell(12);
	
@include breakpoint(medium) {
	@include xy-cell(8);
}
```
outputs
```
.contacts {
  width: calc(100% - 1.875rem);
  margin-right: 0.9375rem;
  margin-left: 0.9375rem;
}

@media print, screen and (min-width: 40em) {
  .contacts {
    width: calc(66.66667% - 1.875rem);
    margin-right: 0.9375rem;
    margin-left: 0.9375rem;
```
I'm not sure is it bug or designed behavior, but based on old float grid behavior, behavior of xy-gutters mixin and some other opened issues, I expected that gutters for xy-cell mixin outside of breakpoint mixin should fallback to the smallest breakpoint instead of the largest.
So I expected to get 

```
.contacts {
  width: calc(100% - 1.25rem);
  margin-right: 0.625rem;
  margin-left: 0.625rem;
}

@media print, screen and (min-width: 40em) {
  .contacts {
    width: calc(66.66667% - 1.875rem);
    margin-right: 0.9375rem;
    margin-left: 0.9375rem;
```
So currently it leads to more coding to get desired result 
```
@include xy-cell(12, $breakpoint: small)
```
or 
```
@include breakpoint(small) {
    @include xy-cell(12)
}
```

Also falling back to the largest breakpoint gutters conflicts with xy-gutters($negative: true) which outputs gutters for every breakpoint.
Version 6.4.4-rc1

**Comment by ncoden** [comment]
Hello @Lazerproof.

For the following test code:
```scss
$breakpoints: (
  small: 0,
  medium: 640px,
  large: 1024px,
  xlarge: 1200px,
  xxlarge: 1440px,
);
$grid-margin-gutters: (
  small: 20px,
  medium: 30px,
);

@import "../foundation-sites/scss/foundation";

.test-no-bp {
  @include xy-cell(12);
}

.test-in-medium {
  @include breakpoint(medium) {
    @include xy-cell(8);
  }
}
```

I got the following CSS:
```css
.test-no-bp {
  width: calc(100% - 1.25rem);
  margin-right: 0.625rem;
  margin-left: 0.625rem;
}

@media print, screen and (min-width: 40em) {
  .test-in-medium {
    width: calc(66.66667% - 1.875rem);
    margin-right: 0.9375rem;
    margin-left: 0.9375rem;
  }
}
```

Could you `@debug -zf-size` inside `@mixin xy-cell()` ([there](https://github.com/zurb/foundation-sites/blob/HEAD/scss/xy-grid/_cell.scss#L109) and [there](https://github.com/zurb/foundation-sites/blob/HEAD/scss/xy-grid/_cell.scss#L118)) ? Thank you.
