### ISSUE TITLE
Foundation Template Build Time

### ISSUE THREAD

**Issue by phifa** [zurb/foundation-sites#10811]
is awfully long. Why? Babel? Webpack? My setup is on a SSD, but in larger project the watcher needs up to a minute to transpile and reload the browser. IMHO build time should be <1s to work fast. Performance is one of the USPs of Foundation and being able to quickly develop a prototype. So, what's stopping this? Would like to hear everybody thoughts on this.

**Comment by marcoValkyriweb** [comment]
Have you tried using yarn? My project compiles in under ten seconds, though admittedly I do clean up a lot of unnecessary modules (that aren't used in my project). Using yarn start, a change reflects/compiles in 1.1s and browsersync refreshes instantly. This is on a i7 4720HQ. 

Using npm, it's 3.2s

**Comment by DanielRuf** [comment]
Which node modules do you use in your build setup?

**Comment by phifa** [comment]
@marcoValkyriweb I am not using yarn. I am literally just using the default setup @DanielRuf and adding a little bit of scss and javascript and it slows down a lot. The build time for production is not what concerns me, more the watch time. HTML changes are detected fast, but JS and SCSS just takes a long time.

**Comment by DanielRuf** [comment]
Isn't gulp used by default? Did you try a clean webpack setup? In my experience an incremental webpack build was much faster.

**Comment by marcoValkyriweb** [comment]
@phifa my JS and SCSS changes are within half a second of saving, npm is also quite fast though.

To use yarn: 
first install global: https://yarnpkg.com/lang/en/docs/install/
in the project root/directory where you run npm start, run yarn once (only for project specific set-up)
Then use yarn start for development and yarn build for production.


https://www.sitepoint.com/yarn-vs-npm/
https://blog.oharagroup.net/npm-v5-3-0-vs-yarn-0-27-5-speed-c9d3be07b557 

Changing SCSS: 
[11:50:41] Starting 'sass'...
[Browsersync] 1 file changed (app.css)
[11:50:42] Finished 'sass' after 1.31 s

For the following code, including adding the file to my main.scss:
```scss
.footer-container {
    background-color: $gray-footer;
    color: white;

    h3 {
        color: white;
    }
    a {
        color: white;
    }
    p {
        margin-bottom: unset;
    }
    svg {
        color: $secondary-blue;
    }
    background: { //added this one to add more specifics
        color: red;
        repeat: unset;
    }
}
```
