### ISSUE TITLE
Breakpoint mixin omits print media type when using a named breakpoint and direction

### ISSUE THREAD

**Issue by rossta** [zurb/foundation-sites#10976]
When using the breakpoint mixin with a named breakpoint *and direction*, print is omitted from the media query when it should be included.
 
#### How to reproduce this bug:

Use the breakpoint for a named media query less-than-or-equal to the print breakpoint and a direction:

```sass
.test {
  @include breakpoint(large) {
    display: none;
  }
}
```

#### What should happen:

When using a named media query (no direction specified) less-than-or-equal to the print breakpoint, the print media type is included in the media query:

```sass
.test {
  @include breakpoint(large) {
    display: none;
  }
}
```
Results in: 
```css
@media print, screen and (min-width: 1024px) {
  .test {
     display: none;
  }
}
```
So, I would expect the following sass
```sass
.test {
  @include breakpoint(large up) {
    display: none;
  }
}
```
to produce the same CSS:
```css
@media print, screen and (min-width: 1024px) {
  .test {
     display: none;
  }
}
```
#### What happened instead:

Though the arguments `large` and `large up` produce the same output for screen, the print media type is omitted for `large up`:
```css
@media screen and (min-width: 1024px) {
  .test {
     display: none;
  }
}
```
The same behavior exists for `small up`, `small down`, `medium up`, etc.

I believe this is because the breakpoint mixin does a key-value lookup based on the [whole string of the $value argument](https://github.com/zurb/foundation-sites/blob/f7aab3d77f3c951f72378aeadd9883a8323adfb6/scss/util/_breakpoint.scss#L150) unlike the breakpoint *function*, which [splits the string on the first word of its $value argument](https://github.com/zurb/foundation-sites/blob/f7aab3d77f3c951f72378aeadd9883a8323adfb6/scss/util/_breakpoint.scss#L43). The result is a named query is not found in the key lookup (since the expected key is `'large up'`, for example, so the [logic to include the print media type here](https://github.com/zurb/foundation-sites/blob/f7aab3d77f3c951f72378aeadd9883a8323adfb6/scss/util/_breakpoint.scss#L169) fails.

I believe the fix is to determine the named media query in the breakpoint mixin based on the first word only of the `$value` argument and possibly to extract the direction for use in the logic to determine whether to include the print media type.

#### Foundation Version(s) you are using:

Foundation 6.4.0

**Comment by DanielRuf** [comment]
Not reproducible with Foudnation Sites 6.4.3

It generates

```css
@media print, screen and (min-width: 64em) {
  .test {
    display: none; } }
```
