### ISSUE TITLE
Unexpected results and manual overwrites for xy-cell() mixin within breakpoints

### ISSUE THREAD

**Issue by glennphilp** [zurb/foundation-sites#11284]
## Test Case and/or Steps to Reproduce

```SCSS
.section--a {
  @include xy-cell(); // 100% width minus the margins -left and -right 

  @include breakpoint(medium) {
    @include xy-cell(25%, $gutter-position: left); // 25% width minus left margin, margin-right 0
  }
}

.section--b {
  @include xy-cell(); // 100% width minus the margins -left and -right

  @include breakpoint(medium) {
    @include xy-cell(75%, false, 0); // 75% width, margins -left and -right 0
  }
}
```
*Manual solution*
```SCSS
.section--a {
  @include xy-cell();

  @include breakpoint(medium) {
    width: calc(25% - $global-gutter);
    margin-left: $global-gutter;
    margin-right: 0;
  }
}

.section--b {
  @include xy-cell();

  @include breakpoint(medium) {
    width: 75%;
    margin-left: 0;
    margin-right: 0;
  }
}
```

## What should happen?
When developing the grid using semantic SCSS mixins the xy-cell() should allow for overwriting width and margin for each breakpoint. For example if I set `xy-cell()` for small, then say medium and up `xy-cell(4 of 12, false, 0)` the mixin should output margin -left and -right set to 0 and calculate the exact width without a subtraction for either gutter.

*Expected outcome:*
```CSS
.section--a {
  width: calc(100% - ($global-gutter * 2));
  margin-left: $global-gutter;
  margin-right: $global-gutter;
}

.section--b {
  width: calc(100% - ($global-gutter * 2));
  margin-left: $global-gutter;
  margin-right: $global-gutter;
}

@media screen and (min-width: 40em) {
.section--a {
  width: calc(25% - $global-gutter);
  margin-left: $global-gutter;
  margin-right: 0; // overwrite
}

.section--b {
  width: 75%;
  margin-left: 0; // overwrite
  margin-right: 0; // overwrite
}
}
```

## What happens instead?
Small breakpoint is fine. The issue is at each breakpoint the developer cannot remove margin/padding from previous even using the variables within the xy-cell().

*Actual outcome:*
```CSS
.section--a {
  width: calc(100% - ($global-gutter * 2));
  margin-left: $global-gutter;
  margin-right: $global-gutter;
}

.section--b {
  width: calc(100% - ($global-gutter * 2));
  margin-left: $global-gutter;
  margin-right: $global-gutter;
}

@media screen and (min-width: 40em) {
.section--a {
  width: calc(25% - ($global-gutter * 2));
  margin-left: $global-gutter;
}

.section--b {
  width: 75%;
}
}
```

## Possible Solution

*I am not sure without making an overly complex mixin.*

## Your Environment

- Foundation version(s) used: 6.4.3

## Checklist (all required):

- [x] I have read and follow the CONTRIBUTING.md document.
- [x] There are no other issues similar to this one.
- [x] The issue title is descriptive.
- [x] The template is correctly filled.
