### ISSUE TITLE
localized off-canvas-position rather than globally declared and tied to breakpoints.

### ISSUE THREAD

**Issue by vikksr** [zurb/foundation-sites#11345]
## What should happen?
Hi guys, Using offcanvas components i had implemented an element which in medium and above devices would cover half the screen and in small devices cover entire screen. Now after updating to latest version of 6.4.3.0 i am not able to set this option locally on class by class basis, Is there an option to set this locally for a class.
```scss
.offcanvas-half-screen_right {
  @include off-canvas-base($background: white, $transition: 0.3s ease-in-out);
  @include breakpoint(small) {
     @include off-canvas-position($position: right, $size: 100%);  
  }
  @include breakpoint(medium) {
     @include off-canvas-position($position: right, $size: 50%);
     transform: translateX(100%);
  }
}
.offcanvas_normal_left {
   @include off-canvas-position($position: left, $size: 250px);  
}
```

## What happens instead?
I tried setting in settings file, this works but it applies globally,  for both left and right side offcanvas elemets.
```scss
$offcanvas-sizes: (
  small: 100%,
  medium: 50%,
  large:  50%,
);
```
## Context
Design was for the same breakpoint, left offcanvas should render with 250px(standard default size) 
and right offcanvas should render 50% or 100% based on the breakpoint. It was originally implemented in 6.3.1 and it was working perfectly but ofter updating to 6.4.3.0 it's broken.

## Your Environment
- Foundation version(s) used: 6.4.3.0
- Browser(s) name and version(s): chrome@latest
- Operating System and version (desktop or mobile): MacOS

## Checklist (all required):
- [x] I have read and follow the CONTRIBUTING.md document.
- [x] There are no other issues similar to this one.
- [x] The issue title is descriptive.
- [x] The template is correctly filled.
