### ISSUE TITLE
$grid-container-padding var doesn't accept anything but pixels / flat number

### ISSUE THREAD

**Issue by heyflo** [zurb/foundation-sites#11395]
## What should happen?
I am trying to use the xy-grid with `vw` as padding on the xy-grid-container and what should be printed should be the values I am filling in, in the _settings.scss

## What happens instead?
It converts anything into `rem`.

## Possible Solution
I have found what is responsible of it, in this file `xy-grid/_gutters.scss`, it takes the values of the padding given and transforms it this way : 

```scss
@elseif (type-of($gutters) == 'number') {
    $gutter: rem-calc($gutters) / 2;

    // Loop through each gutter position
    @each $value in $gutter-position {
      #{$gutter-type}-#{$value}: unquote("#{$operator}#{$gutter}");
    }
  }
```

What could be done is if the value is not a flat number or a map just apply this `$gutter: $gutters / 2;`. I'm trying to find a solution using the sass function `type-of()` with `unit()`. Any help on this would be appreciated ✌️

## Test Case and/or Steps to Reproduce
Just use : `$grid-container-padding: 5vw;` in your `_settings.scss` for example and build your css file. You'll see the padding on any of your container calling for `@include xy-grid-container;` are still in rem.

## Context
It would be useful for fluid layout relying on % or vh/vw.

Thanks a lot 👍

**Comment by heyflo** [comment]
Yes but the file using `rem-calc()` is one from the framework (located in the `node_modules` for my case), it uses `rem-calc()` by default on most of the values you're using in **your** `_settings.scss ` file.

I have found a way to change this behavior, but it's not really a safe way of doing it as I modified the file directly in the `node_modules`, `node_modules/foundation-sites/scss/xy-grid/_gutters.scss`:

```scss
// Foundation for Sites by ZURB
// foundation.zurb.com
// Licensed under MIT Open Source

////
/// @group xy-grid
////

/// Create gutters for a cell/container.
///
/// @param {Number|Map} $gutters [$grid-margin-gutters] - Map or single value for gutters.
/// @param {Keyword} $gutter-type [margin] - Type of gutter to output. Accepts either margin or padding.
/// @param {List} $gutter-position [right left] - The position to apply gutters to. Accepts `top`, `bottom`, `left`, `right` in any combination.
/// @param {Boolean} $negative [false] - Whether to apply the gutter as a negative value. Commonly used for nested grids.
@mixin xy-gutters(
  $gutters: $grid-margin-gutters,
  $gutter-type: margin,
  $gutter-position: right left,
  $negative: false
) {
  $operator: if($negative, '-', '');

  // If we have declared negative gutters, force type to `margin.
  $gutter-type: if($negative, 'margin', $gutter-type);

  // Output our margin gutters.
  @if (type-of($gutters) == 'map') {
    @include -zf-breakpoint-value(auto, $gutters) {
      $gutter: rem-calc($-zf-bp-value) / 2;

      // Loop through each gutter position
      @each $value in $gutter-position {
        #{$gutter-type}-#{$value}: unquote("#{$operator}#{$gutter}");
      }
    }
  }
  // Modified this one with a check if it's a flat number or a px usage
  @elseif (type-of($gutters) == 'number' and (unitless($gutters) or unit($gutters) == 'px')) {
    $gutter: rem-calc($gutters) / 2;

    // Loop through each gutter position
    @each $value in $gutter-position {
      #{$gutter-type}-#{$value}: unquote("#{$operator}#{$gutter}");
    }
  }
  // New condition if it's a number but not unitless and not using px
  @elseif (type-of($gutters) or 'number' and unitless($gutters) != 'false' and unit($gutters) != 'px') {
    $gutter: $gutters / 2;

    // Loop through each gutter position
    @each $value in $gutter-position {
      #{$gutter-type}-#{$value}: unquote("#{$operator}#{$gutter}");
    }
  }
  
}
```

So far it's working in both cases now. Unitless value, pixel value, percentages & vh/vw units.

**Comment by DanielRuf** [comment]
> So far it's working in both cases now. Unitless value, pixel value, percentages & vh/vw units.

You can try `patch-package` to create a patch and test it with your project.

If it works a PR would be awesome =)

**Comment by heyflo** [comment]
> You can try `patch-package` to create a patch and test it with your project.
I will try thanks!

And I will submit a PR later today or tomorrow 👍

**Comment by SassNinja** [comment]
Supporting other values than `rem` is a good idea 👍 

But @heyflo when you create a PR please consider a map as well (your example only handles type number).
It should also be possible to use sth like
```scss
$grid-margin-gutters: (
  small: 2vw,
  medium: 4vw
);
```

**Comment by heyflo** [comment]
Yes, you are right. I am going to add that aswell. It is going to take a bit more time before I submit a PR though, I am in a rush on my project, so maybe this weekend or next monday at best.

It is on my todo ✌️

**Comment by heyflo** [comment]
I'm thinking of a possible solution for that map, I cannot test it just now but posting it for later tests (or if anyone can test it while I'm not on the block).
Still modifying the `node_modules/foundation-sites/scss/xy-grid/_gutters.scss` file :
```scss
// Foundation for Sites by ZURB
// foundation.zurb.com
// Licensed under MIT Open Source

////
/// @group xy-grid
////

/// Create gutters for a cell/container.
///
/// @param {Number|Map} $gutters [$grid-margin-gutters] - Map or single value for gutters.
/// @param {Keyword} $gutter-type [margin] - Type of gutter to output. Accepts either margin or padding.
/// @param {List} $gutter-position [right left] - The position to apply gutters to. Accepts `top`, `bottom`, `left`, `right` in any combination.
/// @param {Boolean} $negative [false] - Whether to apply the gutter as a negative value. Commonly used for nested grids.
@mixin xy-gutters(
  $gutters: $grid-margin-gutters,
  $gutter-type: margin,
  $gutter-position: right left,
  $negative: false
) {
  $operator: if($negative, '-', '');

  // If we have declared negative gutters, force type to `margin.
  $gutter-type: if($negative, 'margin', $gutter-type);

  // Output our margin gutters.
  @if (type-of($gutters) == 'map') {
    @include -zf-breakpoint-value(auto, $gutters) {
      // We have a map, now test if the map is either number based and unitless or in pixels
      @if (type-of($-zf-bp-value) == 'number' and (unitless($gutters) or unit($gutters) == 'px')) {
         $gutter: rem-calc($-zf-bp-value) / 2;
       }
       // Or still a number and anything but pixels (%, vw, vh, etc)
       @elseif (type-of($gutters) == 'number' and unitless($gutters) != 'false' and unit($gutters) != 'px') {
         $gutter: $-zf-bp-value / 2;
       }

      // Loop through each gutter position
      @each $value in $gutter-position {
        #{$gutter-type}-#{$value}: unquote("#{$operator}#{$gutter}");
      }
    }
  }
  // Modified this one with a check if it's a flat number or a px usage
  @elseif (type-of($gutters) == 'number' and (unitless($gutters) or unit($gutters) == 'px')) {
    $gutter: rem-calc($gutters) / 2;

    // Loop through each gutter position
    @each $value in $gutter-position {
      #{$gutter-type}-#{$value}: unquote("#{$operator}#{$gutter}");
    }
  }
  // New condition if it's a number but not unitless and not using px
  @elseif (type-of($gutters) == 'number' and unitless($gutters) != 'false' and unit($gutters) != 'px') {
    $gutter: $gutters / 2;

    // Loop through each gutter position
    @each $value in $gutter-position {
      #{$gutter-type}-#{$value}: unquote("#{$operator}#{$gutter}");
    }
  }
  
}
```
I'll probably have time to test it tomorrow by the end of the day.

**Comment by ncoden** [comment]
Hello there!

Thank you @heyflo for the suggestion. It could be interesting to support others values when provided, but this is definitely not something we would support directly in the `xy-gutters` mixin.

I think we have two solution:
- Add support of others units to `rem-calc()` (and maybe rename it?). But we would have to make sure that everywhere we use `rem-calc()` we also support non-pixel values (so no `+ 1` / `- 1`)
- Otherwise, add an other function to support others units (and convert to rem when possible) and use it when relevant. This should be correctly commented otherwise.

**Comment by heyflo** [comment]
I think it might be overcomplicating things as you just need to check if its either px or a flat value before doing something pretty simple (dividing by two and applying the result to margin-left/right or padding-left/right). Also I don't understand your statement as it is specifically in the `xy-gutters` mixin that all the work is done. Which does make sense, because the values you are filling are indeed gutters you expect to be applied to your grid system (`$grid-container-padding` and/or `$grid-margin-gutters` and/or `$grid-padding-gutters`).

I have found a way to implement it to a project I had to have a fluid container, also implementing the request from @SassNinja : 

```scss
// Foundation for Sites by ZURB
// foundation.zurb.com
// Licensed under MIT Open Source

////
/// @group xy-grid
////

/// Create gutters for a cell/container.
///
/// @param {Number|Map} $gutters [$grid-margin-gutters] - Map or single value for gutters.
/// @param {Keyword} $gutter-type [margin] - Type of gutter to output. Accepts either margin or padding.
/// @param {List} $gutter-position [right left] - The position to apply gutters to. Accepts `top`, `bottom`, `left`, `right` in any combination.
/// @param {Boolean} $negative [false] - Whether to apply the gutter as a negative value. Commonly used for nested grids.
@mixin xy-gutters(
  $gutters: $grid-margin-gutters,
  $gutter-type: margin,
  $gutter-position: right left,
  $negative: false
) {
  $operator: if($negative, '-', '');

  // If we have declared negative gutters, force type to `margin.
  $gutter-type: if($negative, 'margin', $gutter-type);

  // Output our margin gutters.
  @if (type-of($gutters) == 'map') {
    @include -zf-breakpoint-value(auto, $gutters) {

      // At this stage $gutter should be null
      $gutter: null;

      // We have a map, now test if the map value is a number and unitless or in pixels (rem-calc() use case)
      @if (type-of($-zf-bp-value) == 'number' and (unitless($-zf-bp-value) or unit($-zf-bp-value) == 'px')) {
        $gutter: rem-calc($-zf-bp-value) / 2;
      }
      // Or still a number and anything but pixels (%, vw, vh, etc, to use without rem-calc())
      @elseif (type-of($-zf-bp-value) == 'number' and unitless($-zf-bp-value) != 'false' and unit($-zf-bp-value) != 'px') {
        $gutter: $-zf-bp-value / 2;
      }

      // Loop through each gutter position
      @each $value in $gutter-position {
        #{$gutter-type}-#{$value}: unquote("#{$operator}#{$gutter}");
      }
    }
  }
  // Modified this one with a check if it's a flat number or a px usage
  @elseif (type-of($gutters) == 'number' and (unitless($gutters) or unit($gutters) == 'px')) {
    $gutter: rem-calc($gutters) / 2;

    // Loop through each gutter position
    @each $value in $gutter-position {
      #{$gutter-type}-#{$value}: unquote("#{$operator}#{$gutter}");
    }
  }
  // New condition if it's a number but not unitless and not using px
  @elseif (type-of($gutters) == 'number' and unitless($gutters) != 'false' and unit($gutters) != 'px') {
    $gutter: $gutters / 2;

    // Loop through each gutter position
    @each $value in $gutter-position {
      #{$gutter-type}-#{$value}: unquote("#{$operator}#{$gutter}");
    }
  }
  
}
```
So far it does the job, I tried it both ways (with vw units / %, and with px).
