### ISSUE TITLE
XY Grid Responsive Adjustments Auto-Sizing  does not work as expected when a preceeding cell contains a link to a Google Map

### ISSUE THREAD

**Issue by blynnc** [zurb/foundation-sites#11796]
Introduction.

I have placed an XY Grid group of Responsive Adjustment Cells in a Container  > Nested Accordian.  The Cell following the Cell containing a link to a Google Map does not behave as expected on Responsive Adjustment.

What should happen?

The cell following the cell containing a link to a Google map should behave as expected on
(correction from previous post) on full width. On responsive adjustment when window gets narrow it behaves as expected by stacking.
![responsive adjustment cells misplaced 2](https://user-images.githubusercontent.com/14908417/62218708-38a8c280-b36a-11e9-843d-a30bc3d1b64e.jpeg)

What happens instead?

The cell following the cell containing a link to a Google map falls below and slighly to the right of the cell containing the link to a Google map.

If I add a cell before the cell with the link to a Google Map, all the Cells work as expected

...

Don't have a suggestion for solution yet - any ideas?

...

## Test Case and/or Steps to Reproduce (for bugs)

Test Case: 

CSS

```css
@charset "UTF-8";
/* CSS Document */
.accordion {
        margin-left: 0;
        background: #ffffff;
        list-style-type: none;
}
.accordion[disabled] .accordion-title {
        cursor: not-allowed;
}
.accordion-item:first-child > :first-child {
        border-radius: 0 0 0 0;
}
.accordion-item:last-child > :last-child {
        border-radius: 0 0 0 0;
}

.accordion-title {
        position: relative;
        display: block;
        padding: 1.25rem 1rem 1.25rem 3rem;
        border: 1px solid #0096CB;
        border-bottom: 0;
        font-size: 1.4rem;
        line-height: 1.8rem;
        color: #ffffff;
        background-color: #02B4F4;
}

:last-child:not(.is-active) > .accordion-title {
        border-bottom: 1px solid #e6e6e6;
        border-radius: 0 0 0 0;
        color:#ffffff;
        background-color:#02B4F4;
        
}
.accordion-title:hover, .accordion-title:focus {
        background-color: #FDBB31;
        border:1px solid #CA9627;
}


.accordion-title::before {
        position: absolute;
        top: 50%;
        right: 1rem;
        margin-top: -1rem;
        content: '+';
        font-size: 2rem;
}
.is-active > .accordion-title::before {
        content: '\2013';
}
.accordion-content {
        display: none;
        padding: 1rem;
        border: 1px solid #e6e6e6;
        border-bottom: 0;
        background-color: #C8F1FF;
        color: #000000;
}
:last-child > .accordion-content:last-child {
        border-bottom: 1px solid #e6e6e6;
}

.event-info{
        color:#000000;
        font-weight:700;

}
```

HTML

```html
<ul class="accordion" data-accordion data-allow-all-closed="true"> 
  <li class="accordion-item  is-active" data-accordion-item>
    <a href="#"class="accordion-title">MONTH</a>
    <div class="accordion-content"  data-tab-content>
            
<ul class="accordion" data-accordion data-allow-all-closed="true">
<li class="accordion-item  is-active" data-accordion-item>
<a href="#" class="accordion-title is-active">EVENT TITLE</a>
 <div class="accordion-content event-description" data-tab-content>
<div class="grid-x">
  <div class="cell large-auto event-info"><p>DATE</p></div>
  <div class="cell large-auto event-info"><p>TIME</p></div>
  <div class="cell large-auto event-info"><p>LOCATION</p></div>
  <div class="cell large-auto event-info"><p><a href="https://www.google.com/maps/place/Santa+Fe+Animal+Shelter+%26+Humane+Society/@35.6600963,-106.0471949,14z/data=!4m8!1m2!2m1!1scat+shelter!3m4!1s0x87185c9db0f96a27:0xf68dc5dfbb0ce7c5!8m2!3d35.658031!4d-106.0599503">Map |  Directions</a></p>
<div class="cell large-auto event-info"><p>Tuesday, July 30</p></div>

</div>
</div>
```

How to reproduce:
1. Download a standard version of Foundation 6.5.3
2. Create an HTML file with all the requisite foundation 6.5.3 code
ad te css code above to an external stylesheet
in the <head> 
<link rel="stylesheet" type="text/css" href="css/foundation.min.css"> 

Add the HTML code above to an HTML Document
![responsive adjustment cell misplaced](https://user-images.githubusercontent.com/14908417/62183881-19357980-b319-11e9-8a78-6bb3c0cc0bf9.jpeg)
![responsive adjustment cell misplaced](https://user-images.githubusercontent.com/14908417/62183899-27839580-b319-11e9-85f0-464e0410d27a.jpeg)

Before the clsing </body> 
 <script src="js/vendor/jquery.min.js"></script> 
<script src="js/vendor/what-input.js"></script> 
<script src="js/vendor/foundation.min.js"></script> 

Note: use the latest version of Jquery.

Context

│   [Optional] How has this issue affected you? What are you trying
│   to accomplish? Providing context helps us come up with a solution
│   that is most useful in the real world.

I was trying to add a link to a Google Map 
`<a href="https://www.google.com/maps/place/Santa+Fe+Animal+Shelter+%26+Humane+Society/@35.6600963,-106.0471949,14z/data=!4m8!1m2!2m1!1scat+shelter!3m4!1s0x87185c9db0f96a27:0xf68dc5dfbb0ce7c5!8m2!3d35.658031!4d-106.0599503">`

in a Responsive Adjustment Cell.
...

Your Environment

│   Include as many relevant details about the context and environment
│   you experienced the bug in. You can also provide logs.

- Foundation version(s) used:  6.5.3
- Browser(s) name and version(s):  Firefox, Safari, Chrome - latest versions
- Device, Operating System and version:  MAC OSX  - latest version of OS
- Link to your project:  Not available

---
│   Please ensure that all the following points are respected.

- [ x] I have read and follow the CONTRIBUTING.md document.
- [ x] There are no other issues similar to this one.
- [x ] The issue title and template are correctly filled.
