### ISSUE TITLE
.close-reveal-modal is unstyled if .reveal-modal-bg is used instead of .reveal-modal

### ISSUE THREAD

**Issue by r3wt** [zurb/foundation-sites#6374]
```css
.reveal-modal .close-reveal-modal {
font-size: 2.22222rem;
line-height: 1;
position: absolute;
top: 0.55556rem;
right: 1.22222rem;
color: #AAAAAA;
font-weight: bold;
cursor: pointer;
}
```

![img](http://puu.sh/gpfLc/6e773feeeb.png)
