### ISSUE TITLE
add $input-placeholder-font-color in foundation_and_overrides.scss in rails

### ISSUE THREAD

**Issue by justinj656** [zurb/foundation-sites#6608]
hi, 
I am using foundation-rails-5.5.2.1, and I find the placeholder color is too light by defaults. However I can't find some variable concerned in foundation_and_overrides.scss

After some grep work, I find the $input-placeholder-font-color is defined in _form.scss

```scss
$input-placeholder-font-color: #cccccc !default; //line 26

...

// line 488
// style placeholder text cross browser 
    ::-webkit-input-placeholder {
      color: $input-placeholder-font-color;
    }

    :-moz-placeholder { /* Firefox 18- */
       color: $input-placeholder-font-color;  
    }

    ::-moz-placeholder {  /* Firefox 19+ */
       color: $input-placeholder-font-color;  
    }

    :-ms-input-placeholder {  
       color: $input-placeholder-font-color;  
    }
```
Should it be defined in the foundation_and_overrides.scss for convenience or to remind us the existence of it??
