### ISSUE TITLE
File Upload Button - Zurb Building Blocks

### ISSUE THREAD

**Issue by revolutionstrike** [zurb/foundation-sites#6988]
File Upload Button from Zurb Building Blocks does not pop up the file select window in Firefox 21.

Building Blocks link: http://zurb.com/building-blocks/file-upload-button

**Comment by jarrydfillmore** [comment]
I have the same issue. Hope this can be fixed soon!

**Comment by gakimball** [comment]
We found a better way to do this which you can use instead.

```html
<label for="exampleFileUpload" class="button">Upload File</label>
<input type="file" id="exampleFileUpload" class="show-for-sr">
```

`.show-for-sr` is in Foundation 6, but not 5. Here's the code for it:

```css
.show-for-sr {
  position: absolute !important;
  width: 1px;
  height: 1px;
  overflow: hidden;
  clip: rect(0, 0, 0, 0);
}
```
