### ISSUE TITLE
Range slider doesn't work in mobile view inside translated div

### ISSUE THREAD

**Issue by tjerabek** [zurb/foundation-sites#7002]
# Description

Range doesn't work in mobile view. I have this code:
## HTML

``` HTML
<div class="a">
<div class="b">
 <div class="item">Item</div>
 <div class="item">Item</div>
 <div class="item">-----slider----</div>
</div>
</div>
```
## CSS:

``` CSS
.a{
 overflow: hidden;
}
.b{
 width: 300%;
}
.item{
 width: 33%;
 float: left;
}
```

There is `transform(translate(-33%, 0))` and `transform(translate(-66%, 0))` on click. Desktop works very well, but mobile doesn't
## Tested on
- iPhone 5s iOS 9
- Chrome simulator
