### ISSUE TITLE
Changing base font size DOES affect grid breakpoints

### ISSUE THREAD

**Issue by designerdean** [zurb/foundation-sites#7021]
I added this issue to the foundation-sites-6 repository but then the official version 6 was released. I tested this bug with the latest release and it is still a problem.

The documentation's indicates that, "if you want your base font size to be different and not have it affect the grid breakpoints, set $rem-base to $global-font-size and make sure $global-font-size is a pixel value" (http://foundation.zurb.com/sites-6-docs/global-styles.html#font-sizing). I've done that but it actually does affect the grid sizing.

As you can see from the attached screenshots, I have set $global-font-size to 22px; and $rem-base to $global-font-size. In the attached browser screenshot, you can see that the "small" breakpoint is being applied before hitting the 550px point (the point I defined in my breakpoint variables, also attached).

![1](https://cloud.githubusercontent.com/assets/729893/11281373/8e325922-8eb7-11e5-8d15-e170840193ae.png)
![2](https://cloud.githubusercontent.com/assets/729893/11281374/8e424d8c-8eb7-11e5-8c8e-b75a90227387.jpg)
![3](https://cloud.githubusercontent.com/assets/729893/11281375/8e49193c-8eb7-11e5-9eb8-de4cafa3afc9.png)

**Comment by erredeco** [comment]
If I remenber, In version 5 I solved this kind of problems in this way:
I defined a function that converts px values to %:
```
@function convert-to-percent($value, $base-value: $rem-base){
  $value: strip-unit($value) / strip-unit($base-value) * 100%;
    @if ($value == 0%) { $value: 0; }
    @return $value;
}
// $rem-base: 16px
```
then on _global.scss:

```
html{
  font-size:100%
}
body{
  font-size: convert-to-percent($base-font-size);
}
```
I will try if the same approach works for FF6

**Comment by designerdean** [comment]
Foundation team: Any update on this?

@erredeco's suggestion made me realize that changing $global-font-size to a bigger or smaller **percentage** kind of works without messing up the media query breakpoints. However, since both `<html>` and `<body>' are given the same value, it takes a percentage of the percentage, making it bigger or smaller than intended.

As I mentioned when opening this issue, the Foundation documentation gives different instructions on setting the global font size.

What is the correct Foundation way to change the base font size?

**Comment by kesy85** [comment]
Same problem here, any news? It's a basic function, please fix it

**Comment by jensengelmann** [comment]
For my understanding it's just a bug in the breakpoint calculation.

If you change the global font-size, the base font-size for the html-tag is set:
```scss
html {
  font-size: 12px;
}
```

Therefore all em/rem values for child elements of <html> are based on 12px... so far so good. To get the calulation of all the widths of the foundation grid working, the $rem-base must be set to 12px too (default is 16px).

```scss
$rem-base: 12px;
```

The $rem-base is used for the function rem-calc which converts pixel values to the rem unit. This function is widely used in foundation sites... also in the breakpoint calculation.

But media queries em values are not based on the base font-size defined in the :root or html element (http://blog.w3conversions.com/2015/03/all-your-base-are-belong-to-us-%E2%80%94-or-what-base-size-do-em-based-media-queries-use/). So foundation does calculate the media queries on the defined $rem-base, but should calculate them with a base of 16px.

Long answer short: change the -zf-bp-to-em function in the _unit.scss and set the base value for the calculation to 16px.
```scss
// Converts a unitless, pixel, or rem value to em, for use in breakpoints.
@function -zf-bp-to-em($value) {
  // Pixel and unitless values are converted to rems
  @if unit($value) == 'px' or unitless($value) {
    // conversion base must be 16, cause for breakpoints it's always 16
    $value: rem-calc($value,16px);
  }

  // Then the value is converted to ems
  @return strip-unit($value) * 1em;
}
```
