### ISSUE TITLE
Collapse on flexbox grid

### ISSUE THREAD

**Issue by jfalk** [zurb/foundation-sites#7065]
Having collapse on the flexbox grid would be very useful

**Comment by aibrean** [comment]
easy enough to manually just add it in:

```css
.row.collapse .columns, .row.collapse .column {
    padding: 0;
}
```
