### ISSUE TITLE
[F6][Responsive Toggle] both menus appear prior to javascript loading

### ISSUE THREAD

**Issue by colin-marshall** [zurb/foundation-sites#7083]
I copied the Responsive Toggle navigation example from the docs and noticed that you can see both the top-bar and the mobile menu for a split second. Once Foundation's javascript loads, one of the two menus disappears, depending on which breakpoint you're at, and it looks normal.

This is easily fixed by:

```scss
.title-bar {	
	@include breakpoint(medium) {
		display: none;
	}
}

.top-bar {
	display: none;

	@include breakpoint(medium) {
		display: block;
	}
}
```

Is there a different/better way to go about this? And is it worth mentioning a fix for this in the docs?

**Comment by gakimball** [comment]
Hm, we probably don't want to hardcode in those styles, because you could use either component for anything, at any screen size.

You could do this:

```scss
.no-js [data-responsive-toggle] {
  display: none;
}
```

This will hide the mobile thing if JavaScript is disabled, only showing the desktop thing (the menu itself). That means on desktop browsers there's no flash, but mobile browsers would get a flash. With the flash, you'd go from seeing the desktop thing only, to seeing the mobile thing only.
