### ISSUE TITLE
[scss] no !default for $button-margin in RTL

### ISSUE THREAD

**Issue by imranomari** [zurb/foundation-sites#7093]
When the` $global-text-direction` is set to **'rtl'**, always `$button-margin` setting gets overridden by this lines:

```scss
// components/_button.scss, line ~ 55

// Internal: flip from margin-right to margin-left for defaults
@if $global-text-direction == 'rtl' {
  $button-margin: 0 0 $global-margin $global-margin;
}
```
