### ISSUE TITLE
Optimize size of generate css

### ISSUE THREAD

**Issue by IllusionPerdu** [zurb/foundation-sites#7094]
An optimization of scss/typography/_alignment.scss
```sass
// Foundation for Sites by ZURB
// foundation.zurb.com
// Licensed under MIT Open Source

@mixin foundation-text-alignment {
    @each $size in $breakpoint-classes {
      @include breakpoint($size) {
        @each $align in (left, right, center, justify) {
          @if $size != 'small' {
            .#{$size}-text-#{$align} {
              text-align: $align;
            }
          }
          @else {            
            .text-#{$align} {
              text-align: $align;
            }
          }
        }
      }
    }
}
```

Produce : 
```css
.text-left {
  text-align: left; }

.text-right {
  text-align: right; }

.text-center {
  text-align: center; }

.text-justify {
  text-align: justify; }

@media screen and (min-width: 40em) {
  .medium-text-left {
    text-align: left; }
  .medium-text-right {
    text-align: right; }
  .medium-text-center {
    text-align: center; }
  .medium-text-justify {
    text-align: justify; } }

@media screen and (min-width: 64em) {
  .large-text-left {
    text-align: left; }
  .large-text-right {
    text-align: right; }
  .large-text-center {
    text-align: center; }
  .large-text-justify {
    text-align: justify; } }
```

The old 
```css
.text-left {
  text-align: left; }

@media screen and (min-width: 40em) {
  .medium-text-left {
    text-align: left; } }

@media screen and (min-width: 64em) {
  .large-text-left {
    text-align: left; } }

.text-right {
  text-align: right; }

@media screen and (min-width: 40em) {
  .medium-text-right {
    text-align: right; } }

@media screen and (min-width: 64em) {
  .large-text-right {
    text-align: right; } }

.text-center {
  text-align: center; }

@media screen and (min-width: 40em) {
  .medium-text-center {
    text-align: center; } }

@media screen and (min-width: 64em) {
  .large-text-center {
    text-align: center; } }

.text-justify {
  text-align: justify; }

@media screen and (min-width: 40em) {
  .medium-text-justify {
    text-align: justify; } }

@media screen and (min-width: 64em) {
  .large-text-justify {
    text-align: justify; } }
```
It reduce near 250 char and it more clear
(sorry for my bad english)
