### ISSUE TITLE
grid-column-end loses specificity battle.

### ISSUE THREAD

**Issue by christianmagill** [zurb/foundation-sites#7112]
When using grid-column-end in a basic way...

.gallery-item{
  @include grid-column(4);
  @include grid-column-end;
}

You end up with the results css selectors... and the grid-column-end selector ends up losing and not being applied.

.gallery-item:last-child:not(:first-child) {
    float: right; // generated by grid-column
}
.gallery-item:last-child {
    float: left; // generated by grid-column-end
}

**Comment by mattferderer** [comment]
The docs on Foundation's size seem to have an extra class that isn't appearing in the current version:

```CSS
.column.end:last-child, .end.columns:last-child {
    float: left; 
}
```
