### ISSUE TITLE
Create Tab SASS Mixins to match Accordion?

### ISSUE THREAD

**Issue by jhned** [zurb/foundation-sites#7114]
TL:DR; Can we break out the tab component's styles into individual mixins? This will allow it to be more adaptable for non-standard situations.

The Accordion component's styles have been broken out in to individual mixins, which allows a developer to apply Accordion styles in a situation where I need to use non-standard classes. 

```scss
@mixin accordion-container {
  list-style-type: none;
  background: $accordion-background;
  border: $accordion-content-border;
  border-radius: $global-radius;
  margin-#{$global-left}: 0;
}

/// Adds styles for the title of an accordion item. Apply this to the link within an accordion item.
@mixin accordion-title {
  display: block;
  padding: $accordion-item-padding;
  line-height: 1;
  font-size: rem-calc(12);
  color: $accordion-item-color;
  position: relative;
  border-bottom: $accordion-content-border;

  &:hover,
  &:focus {
    background-color: $accordion-item-background-hover;
  }

  // Remove the border on the last title
  :last-child > & {
    border-bottom-width: 0;
  }

  @if $accordion-plusminus {
    &::before {
      content: '+';
      position: absolute;
      #{$global-right}: 1rem;
      top: 50%;
      margin-top: -0.5rem;
    }

    .is-active > &::before {
      content: '–';
    }
  }
}

/// Adds styles for accordion content. Apply this to the content pane below an accordion item's title.
@mixin accordion-content {
  padding: $accordion-item-padding;
  display: none;
  border-bottom: $accordion-content-border;
}

@mixin foundation-accordion {
  .accordion {
    @include accordion-container;
  }

  .accordion-item {
    // This class doesn't need styles!
  }

  .accordion-title {
    @include accordion-title;
  }

  .accordion-content {
    @include accordion-content;
  }
}
```

The Tab component's styles have not been broken out, but it would help me out a lot if they were. Here's what they look like right now: 

```scss
@mixin foundation-tabs {
  .tabs {
    @include clearfix;
    margin: $tab-margin;
    list-style-type: none;
    background: $tab-background;
    border: 1px solid $tab-content-border;

    // Simple
    &.simple {
      > li > a {
        padding: 0;

        &:hover {
          background: transparent;
        }
      }
    }

    // Vertical
    &.vertical {
      > li {
        width: auto;
        float: none;
        display: block;
      }
    }

    // Primary color
    &.primary {
      background: $primary-color;

      > li > a {
        color: foreground($primary-color);

        &:hover,
        &:focus {
          background: smart-scale($primary-color);
        }
      }
    }
  }

  .tabs-title {
    float: #{$global-left};

    > a {
      display: block;
      padding: $tab-item-padding;
      line-height: 1;
      font-size: 12px;
      color: $tab-item-color;

      &:hover,
      &:focus,
      &[aria-selected="true"] {
        background: $tab-background-active;
      }
    }
  }

  .tabs-content {
    background: $tab-content-background;
    transition: all 0.5s ease;
    border: 1px solid $tab-content-border;
    border-top: 0;

    &.vertical {
      border: 1px solid $tab-content-border;
      border-#{$global-left}: 0;
    }
  }

  .tabs-panel {
    display: none;
    padding: $tab-content-padding;

    &.is-active {
      display: block;
    }
  }
}
```
