### ISSUE TITLE
[Naming] `vertical-center` mixin is misleading

### ISSUE THREAD

**Issue by HugoGiraudel** [zurb/foundation-sites#7135]
The `vertical-center` mixin (see below) is actually centering both horizontally and vertically, therefore should be named `absolute-center`.

```scss
/// Vertically and horizontally centers an element using `transform`.
@mixin vertical-center {
  position: absolute;
  top: 50%;
  left: 50%;
  transform: translate(-50%, -50%);
}
```

On top of that, the `v-align-middle` mixin (see below) —which actually only centers vertically— should be named `vertical-center` for consistency.

```scss
/// Vertically centers an element using `transform`.
@mixin v-align-middle {
  position: absolute;
  top: 50%;
  transform: translateY(-50%);
}
```

**Comment by gakimball** [comment]
Yeah, I meant to rename these before the framework shipped. Arguably you could combine both into one mixin, and specify if you want a vertical center, horizontal center, or both. Would you be interested in writing this?

**Comment by HugoGiraudel** [comment]
Something like this: http://www.sitepoint.com/centering-with-sass/?

I’d go with 3 mixins anyway:

```scss
// Vertically centers the element in its first non-static ancestor
@mixin vertical-center {
  position: absolute;
  top: 50%;
  transform: translateY(-50%);
}

// Horizontally centers the element in its first non-static ancestor
@mixin horizontal-center {
  position: absolute;
  left: 50%;
  transform: translateX(-50%);
}

// Absolutely centers the element in its first non-static ancestor
@mixin absolute-center {
  position: absolute;
  top: 50%;
  left: 50%;
  transform: translate(-50%, -50%);
}
```
