### ISSUE TITLE
[Improvement] `auto-width` mixin’s default arguments

### ISSUE THREAD

**Issue by HugoGiraudel** [zurb/foundation-sites#7136]
I would argue the default value for the `$elem` argument of the `auto-width` mixin should be `&` (the current selector reference) rather than `li`. The latter is quite arbitrary and while it might fit in many situations, relying on `&` is actually a safer bet as it relies on context.

Thoughts on this?

**Comment by gakimball** [comment]
The selectors you get out of `&` don't work quite right in some contexts. Here's button group:

```css
.button-group.expanded .button:nth-last-child(2):first-child,
  .button-group.expanded .button:nth-last-child(2):first-child ~ .button-group.expanded .button {
    width: 50%; }
```

The selector after the `~` is `.button-group.expanded .button`. That has to be just `.button` for the selector to apply.

For now we'll keep it as is. Now, for the two components that use quantity queries, Menu and Button Group, it's been suggested that we switch to `display: table-cell` to cut down on the CSS trickery. If that works out, there will be less of a need for this mixin.

**Comment by HugoGiraudel** [comment]
What Sass version do you support? Because a clever way would be to take the
last part of the selector if you want to do things right. I could help with
that.

Le mer. 25 nov. 2015 00:49, Geoff Kimball <notifications@github.com> a
écrit :

**Comment by gakimball** [comment]
@HugoGiraudel We support Libsass 3.4 and Ruby Sass 3.4. If a Libsass bug comes up, I tend to work around it to accommodate it, since all of our stuff uses node-sass.

I had looked at using the selector functions to split the selector and grab the last item, but I was too lazy to implement it :P If you want to do it I'll totally pull it in.

**Comment by HugoGiraudel** [comment]
Here you go.

## Code

```scss
@mixin auto-width($max) {
  // Iterate over the selectors if the selector is composed of many (e.g. `.foo, .bar`)
  @each $selector in & {
    // Print at root to avoid duplicated selectors
    @at-root {
      @for $i from 2 through $max {
        // Base is current selector, and siblings are using last part of current selector
        #{$selector}:nth-last-child(#{$i}):first-child,
        #{$selector}:nth-last-child(#{$i}):first-child ~ #{nth($selector, -1)} {
          width: percentage(1 / $i);
        }
      }
    }
  }
}
```

## Tests

Selector A:

```scss
.main ol li {
  @include auto-width(4);
}
```

Yields:

```css
.main ol li:nth-last-child(2):first-child,
.main ol li:nth-last-child(2):first-child ~ li {
  width: 50%;
}

.main ol li:nth-last-child(3):first-child,
.main ol li:nth-last-child(3):first-child ~ li {
  width: 33.33333%;
}

.main ol li:nth-last-child(4):first-child,
.main ol li:nth-last-child(4):first-child ~ li {
  width: 25%;
}
```

Selector B:

```scss
.baz {
  @include auto-width(3);
}
```

```css
.baz:nth-last-child(2):first-child,
.baz:nth-last-child(2):first-child ~ .baz {
  width: 50%;
}

.baz:nth-last-child(3):first-child,
.baz:nth-last-child(3):first-child ~ .baz {
  width: 33.33333%;
}
```

Selector C:

```scss
.foo, .bar {
  @include auto-width(3);
}
```

```css
.foo:nth-last-child(2):first-child,
.foo:nth-last-child(2):first-child ~ .foo {
  width: 50%;
}

.foo:nth-last-child(3):first-child,
.foo:nth-last-child(3):first-child ~ .foo {
  width: 33.33333%;
}
.bar:nth-last-child(2):first-child,
.bar:nth-last-child(2):first-child ~ .bar {
  width: 50%;
}

.bar:nth-last-child(3):first-child,
.bar:nth-last-child(3):first-child ~ .bar {
  width: 33.33333%;
}
```
