### ISSUE TITLE
[Improvement] Possible unnecessary variable in `background-triangle`

### ISSUE THREAD

**Issue by HugoGiraudel** [zurb/foundation-sites#7137]
```scss
@mixin background-triangle($color: $black) {
  $rgb: 'rgb(#{red($color)}, #{green($color)}, #{blue($color)})';

  background-image: url('data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" version="1.1" width="32" height="24" viewBox="0 0 32 24"><polygon points="0,0 32,0 16,24" style="fill: #{$rgb}"></polygon></svg>');

  // ...
}
```

I am not entirely sure why:

- you need the `$rgb` variable at all. I would say you can print `$color` inside your string directly.
- you need it as a string since you interpolate it anyway. You can leave it as a color, like so: `$rgb: rgb(red($color), green($color), blue($color))`.
- you are exploding the `$color` variable only to make it `rgb` again. Do you absolutely need a `rgb(..)` format? I am pretty sure hex is supported here as well.

Anything I’m missing?
