### ISSUE TITLE
$topbar-link-color doesn't seem to be used anywhere

### ISSUE THREAD

**Issue by JoelESvensson** [zurb/foundation-sites#7156]
The variable $topbar-link-color is listed in _settings.scss but it doesn't actually change anything

**Comment by ChiliConSql** [comment]
Same problem here. Looking at scss/components/_top-bar.scss, I see $topbar-background(which works) but no $topbar-link-color. Is this a mistake? Does someone know how to do a quick fix?

**Comment by colin-marshall** [comment]
This is messy but it should work:

```scss
.top-bar > ul > li > a {
  color: $white;
  &:hover {
    color: $blue;
  }
}
```
