### ISSUE TITLE
[Dropdown Menus] Submenu alignment

### ISSUE THREAD

**Issue by brettsmason** [zurb/foundation-sites#7169]
Submenus are not aligned quite right on dropdowns.
This is viewable on the docs, and seems to be caused by the border applied to the menu. Removing the border from settings.scss fixes the alignment. See attached screenshot (Item1 subB is the easiest to see it on).

![dropdown-alignment](https://cloud.githubusercontent.com/assets/73229/11361254/237f5794-9284-11e5-8711-8b0ca1243eb8.jpg)

**Comment by imranomari** [comment]
can be solved using something like this:

```scss
.dropdown.menu {
  .submenu {
    // ...
    $submenu-border-width: nth($dropdown-border, 1);
    @if (type_of($submenu-border-width) == 'number') { // if the user didn't set `none`
      margin-top: (-$submenu-border-width);
    }
  }
}
```
