### ISSUE TITLE
Fieldset don't have the border

### ISSUE THREAD

**Issue by designerno1** [zurb/foundation-sites#7194]
i found that the fieldset doesn't have the border configured in settings
output css is
```css
fieldset {
  border: 0;
  padding: 0;
  margin: 0; }

legend {
  margin-bottom: 0.5rem; }

.fieldset {
  border: 1px solid #cacaca;
  padding: 1.25rem;
  margin: 1.125rem 0; }
  .fieldset legend {
    background: #fefefe;
    padding: 0 0.1875rem;
    margin: 0;
    margin-left: -0.1875rem; }
```
_fieldset.scss
```scss
@mixin foundation-form-fieldset {
  fieldset {
    border: 0;
    padding: 0;
    margin: 0;
  }

  legend {
    margin-bottom: $form-spacing * 0.5;
  }

  .fieldset {
    @include fieldset;
  }
}
```
shouldn't it be
```scss
@mixin foundation-form-fieldset {
  fieldset {
    border: 0;
    padding: 0;
    margin: 0;
  }

  legend {
    margin-bottom: $form-spacing * 0.5;
  }

  fieldset {
    @include fieldset;
  }
}
```
