### ISSUE TITLE
Grid .row Not Abiding Max-Width

### ISSUE THREAD

**Issue by EricWizKidOdom** [zurb/foundation-sites#7195]
Complete download of Foundation from [download page](http://foundation.zurb.com/sites/download.html/), foundation.css, line 420
```css
.row {
    max-width: 62.5remrem;
    margin-left: auto;
    margin-right: auto;
}
```

Should be
```css
.row {
    max-width: 62.5rem;
    margin-left: auto;
    margin-right: auto;
}
