### ISSUE TITLE
Dropdown Menu: Last Item Dropdown Positioning Bug

### ISSUE THREAD

**Issue by JeremyEnglert** [zurb/foundation-sites#7251]
If the last item in a menu is a dropdown, the dropdown isn't positioned quite right. I'm assuming its shifting left to avoid the edge of the browser, but it's shifting pretty far left.

The dropdown below is the the "Page With Posts" menu item.

![screen shot 2015-11-26 at 8 52 41 pm](https://cloud.githubusercontent.com/assets/6110968/11433797/de7bbc48-947f-11e5-8696-b003c97fd408.png)

**Comment by zurbchris** [comment]
@designerno1 @JeremyEnglert 
damn... caused by the border, I suspect. Edge detection just tells the JS if something is clear, not by how much or in what direction. Possibly solvable, albeit temporarily, with an equivalent margin-right on the last link in the dropdown.
That aside, lemme think a for a couple minutes on this one.

**Comment by apcrane** [comment]
I am also seeing this issue on the dropdown menu and I am using the latest version (6.0.5). I was just wondering if there was a solution for this yet? 

![dropdown-issue](https://cloud.githubusercontent.com/assets/5689025/11714112/ae5ca01c-9f2f-11e5-81ee-7a568b12c316.PNG)

**Comment by apcrane** [comment]
Found a fix that seems to work for me, although haven't fully tested this yet. But I just changed right:100% to right: 0 via an overrides.scss file:

```
.dropdown.menu .is-dropdown-submenu-parent.opens-left .submenu {
  right: 0;
}
```

**Comment by designerno1** [comment]
+1
looks good for me
_dropdown-menu.scss
change
```scss
.is-dropdown-submenu-parent.opens-left .submenu {
      left: auto;
      right: 100%;
    }
```
to
```scss
.is-dropdown-submenu-parent.opens-left .submenu {
      left: auto;
      right: 0;
    }
```
solve the problem for me too
don't checked if this effects for example align-right menus

**Comment by nska02** [comment]
@apcrane @designerno1 fyi, your fix makes nested dropdown menus overlap each other

<img width="231" alt="screen shot 2015-12-16 at 14 54 19" src="https://cloud.githubusercontent.com/assets/11373782/11842614/f20c187c-a404-11e5-82a0-e66763c85593.png">

**Comment by designerno1** [comment]
you are right thinking about it

**Comment by designerno1** [comment]
quick and dirty fix
```css
.is-dropdown-submenu-parent.opens-left .submenu {
    left: auto;
    right: 0;
  }
  .is-dropdown-submenu-parent .is-dropdown-submenu-parent.opens-left .submenu {
    left: auto;
    right: 100%;
  }
```

**Comment by apcrane** [comment]
Thanks, I've added this in and all ok. Although I don't have any nested dropdowns in the instance I'm using it for.

**Comment by JeremyEnglert** [comment]
I saw that this was fixed in 6.1, but I'm still experiencing this issue even after updating to 6.1.1.

**Comment by zurbchris** [comment]
It should be fixed now, based on my local stuff and codepen samples. If anyone is still having this issue, please let us know, otherwise I'll close this issue on Monday 1/11.
![screen shot 2016-01-08 at 11 36 51 am](https://cloud.githubusercontent.com/assets/13631168/12207573/42a978d4-b5fc-11e5-9f8f-b27a33a081f8.png)

**Comment by JeremyEnglert** [comment]
@zurbchris - I used bower to pull down 6.1.1 and I'm still getting the issue.

Demo link here: http://jointswp.staging.wpengine.com/demo/

**Comment by zurbchris** [comment]
Ahhh! Ok, the (less than ideal) solution, though in my mind close to the correct way to handle this is adding the `align-right` class to the dropdown menu. Since it is visually aligned to the right of the page, you need that class, otherwise, the js has to spend a lot more time calculating for collisions and trying to correct it, when you could just add a class and it's done. One caveat to that, which is what makes it less than ideal, is you have to manually add back the `float: left;` to the li's in the menu.

In summation, using the `align-right` class when your menu is visually aligned to the right of the viewport is the answer, and then to maintain the order floating the li's left. I know there's a way to do this properly with the sass functions we have, and conditionally add the float direction based on ltr/rtl, but that will have to wait for a patch.

Here's a screencap of your demo page after I fiddled with it, hopefully that's what you're looking for. 
![screen shot 2016-01-08 at 2 19 51 pm](https://cloud.githubusercontent.com/assets/13631168/12211035/427a91c4-b613-11e5-987f-28a7c67db1ca.png)

**Comment by Baedda** [comment]
I am using Foundation 6.1.1 via bower and have the same issue. As many people here have written before the following code (at the comment) can fix the issue:

```scss
.menu {
    @include menu-base;
    @include menu-direction(vertical);
    @include breakpoint(large) {
        @include menu-direction(horizontal);
    }
    > .is-dropdown-submenu-parent {
        > a {
            color: $black;
            font: {
                size: $nav-font-size;
            }
        }
        &:hover {
            background: {
                color: $black;
            }
            > a {
                color: $white;
                &:hover,
                &:focus {
                    color: $nav-font-hover-color;
                }
            }
        }
        &.opens-left {
            > .submenu {
                // Foundation Bugfix
                // https://github.com/zurb/foundation-sites/issues/7251
                right: 0 !important;
            }
        }
    }
}
```

It would be really nice to see a fix in the core here. I dont want to add the align-right class manually.
