### ISSUE TITLE
Scrolling / positioning issues with full screen Reveal modal popups in Safari on iOS 8/9 using Foundation 6.0.4

### ISSUE THREAD

**Issue by rickcurran** [zurb/foundation-sites#7282]
I'm encountering scrolling / positioning issues with full screen Reveal modal popups in Safari on iOS 8 / 9 using Foundation 6.0.4. 

The popups open in full screen but scrolling around the page the underlying page content appears and the modal moves around with the content. This should stay fixed in place allowing scrolling only for the modal content and none of the underlying page content should ever be visible.

**Comment by zurbrandon** [comment]
This one we're still struggling with, do you have thoughts as to how to best fix it? Looks like safari on ios isn't respecting our overflow hidden.

**Comment by rickcurran** [comment]
I'm not sure how to fix it specifically for Foundation 6, I ended up implementing my own full screen popup in the meantime as I needed something for a project I was working on. I did look at the Foundation 6 code but there's a lot going on in there and I'm not familiar with it.

There did seem to be a few things online discussing whether it should be using position:fixed and / or other parameters. In the end the custom full screen popup I used had something like the following HTML / CSS:

```html
<div id="pop_menu">
  // popup content here...
<button class="close-button" data-close aria-label="Close reveal" type="button"><span aria-hidden="true">&times;</span></button>
</div>
```

```css
#pop_menu {
  top:0;
  bottom:0;
  position:fixed;
  overflow-y:auto;
  overflow-x:hidden;
  display:none;
  margin-top:0;
  left: 0;
  width: 100%;
  height: 100%;
  height: 100vh;
  min-height: 100vh;
  max-width: none;
  margin-left: 0;
  background:#000;
  padding:0;
  border:none; 
  border-top:10px solid #2c2c2c;
  z-index:99;
}
```

I was then handling some scroll issues in JavaScript for when the full screen popup was opened / closed:

```javascript
$('#pop_menu_trigger').on('click', function(event) {
    $('#pop_menu').show(); 
    $('body').css('overflow-y','hidden');
    event.preventDefault();
});

$('#pop_menu .close-button').on('click', function(event) {
    $('#pop_menu').hide(); 
    $('body').css('overflow-y','auto');
    event.preventDefault();
});
```

Not sure if that helps at all but I think that's what worked on the project I needed it for.
