### ISSUE TITLE
foundation 6 body doesn't clear children

### ISSUE THREAD

**Issue by r3wt** [zurb/foundation-sites#7315]
![img](http://puu.sh/lElwZ/a351223e79.png)
only change made to css of body:

```css
body {
	opacity: 1;
	background-image: linear-gradient(to bottom, #ECECEC, #CFCFD1);
}
```

caused by:

```css
html, body {
    height: 100%;
}
```
