### ISSUE TITLE
[Docs: Media Queries]: Include them like F5

### ISSUE THREAD

**Issue by GBratsos** [zurb/foundation-sites#7474]
Hello,

I started using F6 for some internal projects and testing.

I tried to find at the Documentation > Media Queries the queries breakpoints but i couldn't find them as a CSS code.

On F5 there are mentioned and the visitor/developer can easily copy them and use them fast ( http://foundation.zurb.com/sites/docs/v/5.5.3/media-queries.html )

So it would be great to have them on the new Documentation too.

What do you think?

**Comment by gakimball** [comment]
The [Sass section](http://foundation.zurb.com/sites/docs/media-queries.html#sass) of the Media Queries docs page explains the `breakpoint()` mixin, which is a new shorthand for writing media queries. Like so:

```scss
// Same as "screen and (min-width: 40em)"
@include breakpoint(medium) {
}
```

The docs also explains the function version of `breakpoint()`, which can be used to inject those media query strings directly:

```scss
@media screen and #{breakpoint(medium)} {
}
```

How do you feel the documentation needs to be clarified?

**Comment by simonrcodrington** [comment]
Howdy.

I'd would be good if the documentation for F6's Media Queries also had the sizes listed for the breakpoints in their EM format when using the standard build, e.g 

```
 @media screen and (min-width: 64em)
```

I think what @GBratsos might have been referring to is 'what is the size of the medium and large profiles' etc. 

The Sass documentation is good and all, but for someone who just downloads the pre-built version, having the default size ranges listed would be handy. 

Regards

**Comment by jensengelmann** [comment]
Made the myself, cause we needed them for some default styling we use in several (and also new) projects.

```scss
/// Legacy variables
/// no idea why they dropped legacy support

$small-up: null;
$small-only: null;
$medium-up: null;
$medium-only: null;
$large-up: null;
$large-only: null;
$xlarge-up: null;
$xlarge-only: null;
$xxlarge-up: null;
$xxlarge-only: null;

@if map-has-key($breakpoints,small) {
  $small-up: breakpoint(small);
  $small-only: breakpoint(small only);
}

@if map-has-key($breakpoints,medium) {
  $medium-up: breakpoint(medium);
  $medium-only: breakpoint(medium only);
}

@if map-has-key($breakpoints,large) {
  $large-up: breakpoint(large);
  $large-only: breakpoint(large only);
}

@if map-has-key($breakpoints,xlarge) {
  $xlarge-up: breakpoint(xlarge);
  $xlarge-only: breakpoint(xlarge only);
}

@if map-has-key($breakpoints,xxlarge) {
  $xxlarge-up: breakpoint(xxlarge);
  $xxlarge-only: breakpoint(xxlarge only);
}
```
