### ISSUE TITLE
[Labels] More dynamic mixin.

### ISSUE THREAD

**Issue by rhernandog** [zurb/foundation-sites#7487]
Hi,

This is a request and not an actual issue.

Labels are a component that I use regularly and I have to customize them on a regular basis. But for that I've created my own mixin in order to pass some specific variables such as padding and font size and not mess with the default label variables or add ugly hacks like this one to override the default values:
```css
.my-custom-label {
  @include label;
  padding: 0.75rem 1rem;
}
```

It would be very nice that Foundation could have such a mixin in order to customize things the Foundation way and keep things more consistent.

Thanks for all your effort!!
Best,
Rodrigo.
