### ISSUE TITLE
[Callout/Button] Color from Parent

### ISSUE THREAD

**Issue by designerno1** [zurb/foundation-sites#7490]
example:
```html
<div class="callout primary">
  <a href="#" class="button secondary">Button</a>
</div>
```
button has
```css
.callout.primary a {
    color: #880c4d;
}
```
