### ISSUE TITLE
[F6] top-bar-left and top-bar-right do not have the same height

### ISSUE THREAD

**Issue by imaia** [zurb/foundation-sites#7595]
Hello folks. I have a top-bar which has a image in the top-bar-left, inside a menu. My top-bar-right only has links and a menu. In this scenario, my top-bar-left height is bigger than my top-bar-right. Is this the correct behavior? A height attribute did not help here.

**Comment by andycochran** [comment]
Adding an image/logo to Top Bar is a customization that will require case-specific CSS. I've managed to do it this way… 
```html
<div class="top-bar">
	<div class="top-bar-left">
		<ul class="menu">
			<li class="logo"><a href="#"><img src="logo.png">Site Title</a></li>
		</ul>
	</div>
	<div class="top-bar-right">
		<ul class="menu">
			<li><a href="#">Link</a></li>
		</ul>
	</div>
</div>
```
```css
.logo {
	font-size: rem-calc(18);
	img {
		display: inline-block;
		height: 2em;
		max-width: none;
		vertical-align: middle;
		margin-top: -0.75em;
		margin-right: 0.5em;
		margin-bottom: -0.75em;
		margin-left: -1rem;
	}
}
```
^ You'll have to customize something like that to meet the needs of you image.
