### ISSUE TITLE
[Orbit] prev and next not visible on white by default

### ISSUE THREAD

**Issue by designerno1** [zurb/foundation-sites#7610]
the buttons vor next and prev are not visible by default until you hover over the button

maybe hover on orbit should show the buttons

**Comment by zurbchris** [comment]
Shouldn't that be on the designer to change the color of the buttons themselves? @gakimball @zurbrandon

**Comment by gakimball** [comment]
What @zurbchris said, it's hard for us to account for varying use-cases, so in this case we defer to the designer to account for what content is in the carousel.

You can do the hover reveal with just CSS, by targeting the `:hover` state of the container, and then applying styles to the controls inside.

```css
.orbit:hover .orbit-next,
.orbit:hover .orbit-previous {
  // Put a more explicit hover state in here
  background-color: rgba(0, 0, 0, 0.75);
}
```
