### ISSUE TITLE
Custom breakpoint: smaller than small

### ISSUE THREAD

**Issue by pedzed** [zurb/foundation-sites#7644]
If you add a custom breakpoint, say `xsmall`, the default will remain at `small`. *Please, read further for clarification.*

This is what I added in my settings:
```scss
$breakpoints: (
  xsmall: 0,
  small: 480px,
  medium: 640px,
  large: 1024px,
  xlarge: 1200px,
  xxlarge: 1440px,
);

$breakpoint-classes: (xsmall small medium large);
```

An example of this issue is that if you add `text-center` in the HTML, it keeps the default alias to `small-text-center`, whereas it should be an alias for `xsmall-text-center`. The workaround is to use `xsmall-text-center` instead of `text-center`.

This is an issue which could be fixed by not hardcoding `small` like in [/scss/typography/_alignment.scss#L9](https://github.com/zurb/foundation-sites/blob/836776f6a900383fec2dfdd9494b922c947a87a4/scss/typography/_alignment.scss#L9):
```scss
@if $size != 'small' {
  .#{$size}-text-#{$align} {
    text-align: $align;
  }
}
@else {
  .text-#{$align} {
    text-align: $align;
  }
}
```

**Edit:** This counts for things like font size as well.
