### ISSUE TITLE
[RTL] Select image position 

### ISSUE THREAD

**Issue by ArabCoders** [zurb/foundation-sites#7685]
Hello,

I have found a little bug in the select CSS, in RTL the image cover the text sometimes, it's directly related to this CSS:-

```css
select {
    height: 2.4375rem;
    padding: .5rem;
    margin: 0 0 1rem;
    font-size: 1rem;
    font-family: inherit;
    line-height: normal;
    color: #8a8a8a;
    background-color: #fafafa;
    border-radius: 0;
    -webkit-appearance: none;
    -moz-appearance: none;
    background-image: url('data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" version="1…on points="0,0 32,0 16,24" style="fill: rgb(51, 51, 51)"></polygon></svg>');
    background-size: 9px 6px;
    background-position: right .5rem center;
    background-repeat: no-repeat;
```
``background-position: right .5rem center;`` should be ``background-position: left .5rem center;``

**Comment by gakimball** [comment]
Are you using the CSS downloaded from the customizer, or the Sass version?

**Comment by ArabCoders** [comment]
css downloaded from the customizer

**Comment by gakimball** [comment]
Downloaded a new RTL build from the customizer and got this. There was a bug with the customizer not properly applying RTL, but it's been fixed.

```css
select {
  height: 2.4375rem;
  padding: 0.5rem;
  border: 1px solid #cacaca;
  margin: 0 0 1rem;
  font-size: 1rem;
  font-family: inherit;
  line-height: normal;
  color: #0a0a0a;
  background-color: #fefefe;
  border-radius: 3px;
  -webkit-appearance: none;
  -moz-appearance: none;
  background-image: url('data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" version="1.1" width="32" height="24" viewBox="0 0 32 24"><polygon points="0,0 32,0 16,24" style="fill: rgb%2851, 51, 51%29"></polygon></svg>');
  background-size: 9px 6px;
  background-position: left 0.5rem center;
  background-repeat: no-repeat; }
```
