### ISSUE TITLE
color setting of button using mixins

### ISSUE THREAD

**Issue by desain86** [zurb/foundation-sites#7688]
I believe in _button.scss the button-style() mixin has a bug in the ordering of if/else statements. The "If" for background-hover should be placed outside of if/else for setting text color. In if/else for color the else should be removed letting the default case happen or setting the variable to the passed in param. Of course, to make it even better the else can check to make sure an actual color of some sort is passed in.

**Comment by gakimball** [comment]
Yeah, the logic here gets a little weird. Does this look more correct? I just removed that lightness check in favor of the `foreground()` function, which does the same thing.

```scss
@mixin button-style(
  $background: $button-background,
  $background-hover: $button-background-hover,
  $color: $button-color
) {
  @if $color == auto {
    $color: foreground($background);
  }

  @if $background-hover == auto {
    $background-hover: scale-color($background, $lightness: -20%);
  }

  background-color: $background;
  color: $color;

  &:hover, &:focus {
    background-color: $background-hover;
    color: $color;
  }
}
```
