### ISSUE TITLE
F6 Top Bar Building Block Page

### ISSUE THREAD

**Issue by badcat** [zurb/foundation-sites#7731]
The F6 Building Block page should likely be updated with the following CSS code changes?
See inline comments below.
http://zurb.com/building-blocks/f6-top-bar

```css
body {
  margin-top: 2rem; }  /* Minor typo - margin not marging.  Only for presentation anyway. */

.title-bar {
  background: #333;
  padding: 0.9rem; }

.top-bar {
  background: #333; }
  .top-bar ul {
    background: #333; }
    .top-bar ul li {
      background: #333; }
      .top-bar ul li a {
        color: #fff; }

.menu-text {
  color: #fff; }
  @media only screen and (max-width: 40em) {
    .menu-text {
      display: none !important; } }

@media only screen and (min-width: 40em) {
  .top-bar .menu:last-child { 
    border-left: 1px solid #4e4e4e; }   /* added .top-bar so it doesn't effect the other places where menu might be used - Like in footer menus. */

  .top-bar .menu:first-child {  
    border-left: none; }   /* added .top-bar so it doesn't effect the other places where menu might be used - Like in footer menus. */

  .top-bar .menu li:not(:last-child) {
    border-right: 1px solid #4e4e4e; } }   /* added .top-bar so it doesn't effect the other places where menu might be used - Like in footer menus. */

.dropdown.menu .submenu {
  border: none; }

.dropdown.menu .is-dropdown-submenu-parent.is-right-arrow > a::after {
  border-color: #fff transparent transparent; }

.is-drilldown-submenu-parent > a::after {
  border-color: transparent transparent transparent #fff; }

.js-drilldown-back::before {
  border-color: transparent #fff transparent transparent; }
```

Thanks for the new Top-Bar!  Would love to see more F6 examples added to the Building Blocks pages.

edit: updated the backticks :)  thanks @tomByrer

**Comment by rafibomb** [comment]
Glad you like this example! We can definitely make changes - it would be helpful to know what the changes you made are and why as well. Thanks!

**Comment by rafibomb** [comment]
Hi @badcat We'll need to know what improvements this CSS makes so we can add it in. Thanks!

**Comment by tomByrer** [comment]
@rafibomb Seems he commented OP.

**Comment by tomByrer** [comment]
I put the [original](http://codepen.io/tomByrer/pen/eJyozj/) & @badcat's edits on [codepen](http://codepen.io/tomByrer/pen/MKrRbX).

Might translate to SCSS soon...

**Comment by badcat** [comment]
@tomByrer @rafibomb thanks - I'd made my comments inline with the css.  Sry - thought it was clear.

**Comment by tomByrer** [comment]
@badcat Welcome!  You can turn on block code highlighting by starting with three backticks; makes it easier to read:
``` scss
body {
margin-top: 2rem; } /* Minor typo - margin not marging. Only for presentation anyway. */

.title-bar {
background: #333;
padding: 0.9rem; }
```
