### ISSUE TITLE
'button-group-expand' Mixin Has Incorrect Documentation

### ISSUE THREAD

**Issue by xthilakx** [zurb/foundation-sites#7738]
After upgrading to Foundation `6.1.1` from `6.0.x`, I noticed that 'button-group-expand' was broken. 

SASS compilation failed:
````
Warning:
Warning: wrong number of arguments (2 for 1) for `button-group-expand'
````
````scss
@include button-group-expand('.button-group', 2);
````

````scss

/// Creates a full-width button group, making each button equal width.
/// @param {Keyword|Number} $count [auto] - Number of buttons inside the button group. Set to `auto` to generate CSS that will account for a variable number of buttons.
/// @param {String} $selector [$buttongroup-child-selector] - Selector for the buttons inside a button group.
@mixin button-group-expand(
  $selector: $buttongroup-child-selector
) {
  display: table;
  table-layout: fixed;
  width: 100%;

  &::before,
  &::after {
    display: none;
  }

  #{$selector} {
    display: table-cell;
    float: none;
  }
}
````

I couldn't investigate more because Github's online diff is broken on this file - `foundation-sites/scss/components/_button-group.scss`

But the [documentation](http://foundation.zurb.com/sites/docs/button-group.html#button-group-expand) states that the mixin accepts two arguments, but looks like that mixin only accepts one argument. Perhaps the documentation needs some work?
