### ISSUE TITLE
Getting value of  $header-sizes ?

### ISSUE THREAD

**Issue by TheAggressive** [zurb/foundation-sites#7809]
How can I get a value of say, small > h2

I tried ```map-get($header-sizes, small, h2)``` but it can't take 3 arguements.

I can't figure out.

Thanks!!

**Comment by gakimball** [comment]
For now in Sass you'd need to do nested calls to `map-get()`, which would be quite annoying.

Add this function to your code to make it easier. Then you can call `map-get-deep($header-sizes, small, h2)`.

```scss
@function map-get-deep($map, $keys...) {
    @each $key in $keys {
        $map: map-get($map, $key);
    }
    @return $map;
}
```
