### ISSUE TITLE
Include a nested-map-get function

### ISSUE THREAD

**Issue by erutan** [zurb/foundation-sites#7826]
I was trying to pull out a header size key to use in a partial and hit the limits of the native map-get. After a little searching I stumbled across this solution by Chris Eppstein. It's a little, uh, verbose, but that's progress for ya.

## example usage: 

```scss
font-size: rem-calc(nested-map-get($header-sizes, large-type, h2));
```

## functions

```scss
@function list-slice($list, $start, $end: length($list)) {
  @if $start > length($list) {
    @return ();
  }
  $new-list: ();
  @for $i from $start through $end {
     $new-list: append($new-list, nth($list, $i), list-separator($list));
  }
  @return $new-list;
}
@function nested-map-get($map, $keys...) {
  @return if(length($keys) == 1,
             map-get($map, nth($keys, 1)),
             nested-map-get(map-get($map, nth($keys, 1)), list-slice($keys, 2)...));
}
```

via: https://github.com/sass/sass/issues/1349#issuecomment-50817692
