### ISSUE TITLE
Fieldset Inconsistency?

### ISSUE THREAD

**Issue by Knight-Yoshi** [zurb/foundation-sites#7834]
Why are there two different rules for the fieldset element
Line 322 in the pre-compiled CSS
```css
fieldset {
  border: 1px solid #c0c0c0;
  margin: 0 2px;
  padding: 0.35em 0.625em 0.75em; }
```
Line 1673 in the pre-compiled CSS
```css
fieldset {
  border: 0;
  padding: 0;
  margin: 0; }
```

Right below that rule is a fieldset class rule that doesn't even match the first fieldset rule 
```css
.fieldset {
  border: 1px solid #cacaca;
  padding: 1.25rem;
  margin: 1.125rem 0; }

.fieldset legend {
    background: #eeeeee;
    padding: 0 0.1875rem;
    margin: 0;
    margin-left: -0.1875rem; }
```

Seems inconsistent and I'm not sure why the first fieldset rule exists if it's going to be replaced by the second.
