### ISSUE TITLE
*-centered with .end not working (v6.1.1)

### ISSUE THREAD

**Issue by marcdittmann** [zurb/foundation-sites#7854]
Hi,

i have an issue where i cannot center the last columns. Please check my example. By adding the .end class it will move to the left because both css rules are stronger then the **small-centered**

**with end:**
```css
.column.end:last-child:last-child, 
.end.columns:last-child:last-child {
    float: left;
}
```

**without end:**
```css
.column:last-child:not(:first-child), 
.columns:last-child:not(:first-child) {
    float: right;
}
```

**default small-centered rule**
```css
.small-centered {
    float: none;
    margin-left: auto;
    margin-right: auto;
}
```

Example:
http://codepen.io/anon/pen/KVqbgO

**Comment by andycochran** [comment]
Why use `.end` with `.[small]-centered`? I'd instead drop the `.end` and use `.medium-[pull,push]-[n]`.

**Comment by rafibomb** [comment]
I agree with @andycochran Not seeing the use case since you can only have a single column centered per row. Can you explain if I'm missing something.

**Comment by zurbrandon** [comment]
Yeah, this is against a use case since center can only be used on one column. I'll close this, but feel free to reopen if you're still confused or we're misconstruing.

**Comment by Ne-Ne** [comment]
Hey @marcdittmann, I found a work around for this, hope it helps:

```html
<div class="small-11 small-centered medium-6 medium-offset-0 medium-uncentered">
...
</div>
```

Then create an override:

```scss
@include breakpoint(small only) {
	float: none !important;
}
```
