### ISSUE TITLE
Grid-column() inside of media query compiles duplicate media queries

### ISSUE THREAD

**Issue by treiber** [zurb/foundation-sites#7901]
So I was just shocked by a super bloated css compiled from a scss. The issue is the following:
```scss
@include breakpoint(medium) {
  .foo { @include grid-column(10); }
}
```
My expected css output would be something like this (one `@media`):
```css
@media screen and (min-width: 40em) {
  .foo {
    padding-left: 0.625rem;
    padding-right: 0.625rem;
    width: 83.33333%;
    float: left;
  }
  .foo:last-child:not(:first-child) {
    float: right;
  }
}
```
But what I get is this mess of duplicate media Queries:
```css
@media screen and (min-width: 40em) {
  .foo {
    padding-left: 0.625rem;
    padding-right: 0.625rem;
    width: 83.33333%;
    float: left;
  }
}
@media screen and (min-width: 40em) and (min-width: 40em) {
  .foo {
    padding-left: 0.9375rem;
    padding-right: 0.9375rem;
  }
}
@media screen and (min-width: 40em) {
  .foo:last-child:not(:first-child) {
    float: right;
  }
}
```

Can someone explain that behavior to me? Is the `grid-column` mixin not supposed to go inside a media Query? Why are there duplicate padding declarations?

**Comment by gakimball** [comment]
Try this instead:

```scss
.foo {
  @include grid-column;

  @include breakpoint(medium) {
    @include grid-column-size(10);
  }
}
```

The extra media query comes from the responsive gutter adjustments on the column. Above, I've moved the base column definition outside of the media query, and then changed the size only at the `medium` breakpoint.

The CSS output of the above code is:

```css
.foo {
  padding-left: 0.625rem;
  padding-right: 0.625rem;
  width: 100%;
  float: left; }
  @media screen and (min-width: 40em) {
    .foo {
      padding-left: 0.9375rem;
      padding-right: 0.9375rem; } }
  .foo:last-child:not(:first-child) {
    float: right; }
  @media screen and (min-width: 40em) {
    .foo {
      width: 83.33333%; } }
```
