### ISSUE TITLE
Add in a $input-border-invalid variable to settings, and call it in forms/_error.scss

### ISSUE THREAD

**Issue by erutan** [zurb/foundation-sites#7935]
My alert color before gave me a nice border color, but the 10% alpha still made it a bit too noticeable. Changing `$input-background-invalid` to an appropriate color now makes the border too light.  

If you really don't want to add a new variable, change `$input-background-invalid` to `$input-border-invalid` since that's how it is being used directly. Probably better than that would to just use $form-label-color-invalid as the border color, as those two should align pretty well.

I can put in a pull if this is OKed.

re:
```scss
@mixin form-input-error(
  $background: $input-background-invalid
) {
  &:not(:focus) {
    background-color: rgba($background, 0.1);
    border-color: $background;
  }
}
```

make this:
```scss
@mixin form-input-error(
  $background: $input-background-invalid, $border: $input-border-invalid
) {
  &:not(:focus) {
    background-color: $background;
    border-color: $border;
  }
}
```

or simply:

```scss
@mixin form-input-error(
  $background: $input-background-invalid, $border: $form-label-color-invalid
) {
  &:not(:focus) {
    background-color: $background;
    border-color: $form-label-color-invalid;
  }
}
```
