### ISSUE TITLE
Accordion title bug

### ISSUE THREAD

**Issue by r3wt** [zurb/foundation-sites#7938]
```css
:last-child > .accordion-title {
    border-bottom-width: 0px;
}
```

should be

```css
.accordion-item:last-child:not(.is-active) > .accordion-title {
    border-bottom-width: 0px;
}
```
