### ISSUE TITLE
[Button] User-defined Sizes

### ISSUE THREAD

**Issue by andycochran** [zurb/foundation-sites#7972]
Currently, button size classes are hardcoded in `_button.scss`:  
```scss
&.tiny     { font-size: map-get($button-sizes, tiny); }
&.small    { font-size: map-get($button-sizes, small); }
&.large    { font-size: map-get($button-sizes, large); }
```

Instead, we could loop through the `$button-sizes` map to allow user-defined button sizes: 
```scss
@each $size, $value in $button-sizes {
  &.#{$size} { font-size: $value; }
}
```
Caveat: It adds a .default button size class.

#7933, addresses this for button group sizes and could be amended to also close this issue.
