### ISSUE TITLE
Split Button: "arrow-only" fault in vertical alignment

### ISSUE THREAD

**Issue by stefan2** [zurb/foundation-sites#8010]
http://foundation.zurb.com/sites/docs/button-group.html#split-buttons

Arrow alignment, value of "top" should lower than "0.2em"

```scss
// components/_button.scss
@mixin foundation-button{
    // [...]
    // Button with dropdown arrow only
    &.arrow-only::after {
      margin-#{$global-left}: 0;
      float: none;
      // top: 0.2em;
      top: -0.1em; // nice alignment
    }
}
```
![current](https://cloud.githubusercontent.com/assets/314437/12577887/b0e3bb28-c41d-11e5-9003-6ab220e729c0.png)
![perfect](https://cloud.githubusercontent.com/assets/314437/12577893/b4bb4eaa-c41d-11e5-84d4-12734e3143c0.png)
![with-dropdown](https://cloud.githubusercontent.com/assets/314437/12578214/b4a7ec32-c41f-11e5-9dde-0a61a15a18ec.png)
same like dropdown button
