### ISSUE TITLE
[Tooltip] Corner arrow not showing properly

### ISSUE THREAD

**Issue by DaGhostman** [zurb/foundation-sites#8057]
I am having an issue with the tooltips not showing correctly, as you can see from the screenshot, the corner which imitates a bubble is not showing correctly.

![this screenshot](https://cloud.githubusercontent.com/assets/2286949/12761050/63f6f090-c9e1-11e5-9f79-0f44b5b9f10a.png)

Here is the relative code:

```
<div class="switch float-left" data-tooltip aria-haspopup="true" title="Toggle the password field making it visible instead of dots">
    <input class="switch-input" id="passwordVisibility" type="checkbox">
    <label class="switch-paddle" for="passwordVisibility">
        <span class="show-for-sr">Toggle Password Visibility</span>
        <span class="switch-active" aria-hidden="true">
            <span class="material-icons">visibility</span>
        </span>
        <span class="switch-inactive" aria-hidden="true" style="color: #1583cc">
            <span class="material-icons">visibility_off</span>
        </span>
    </label>
</div>
```

the container tag is a `div.medium-6.medium-offset-3.columns` without any custom styling.

The issue is present in FireFox 44.0 and  Google Chrome 48.0.2564.97 both running with on Ubuntu 14.04, all is up to date

**Comment by gakimball** [comment]
Not able to recreate this. The icons aren't there, but the tooltip works fine:

![image](https://cloud.githubusercontent.com/assets/1142001/12834389/d569047c-cb5b-11e5-9bfd-0ab92787a6d0.png)

We'll need to see any CSS applied to this to figure out what's wrong.

**Comment by DaGhostman** [comment]
I was able to isolate the issue! The only way I can get it to show up properly is only when I use the `foundation.css` file instead of `foundation.min.css`.

Foundation version 6.1.2 installed using bower

**Comment by gakimball** [comment]
Very interesting. Could you try comparing the two using your browser's web inspector, seeing if there are any differences in the CSS output?

I think the bug is coming from the CSS compressor messing up the `border` in the tooltip pip, which has a particular structure to make the triangle look right.

**Comment by DaGhostman** [comment]
Sorry for the delayed response, I'll check that today.

**Comment by DaGhostman** [comment]
Sorry again for the delay, some stuff came up. Unfortunately I am not able to identify the problem, myself. 

But it appears that it is related to the compressor as the issue persists when using latest `6.2.0`

**Comment by stephenhowells** [comment]
I can confirm that I see the same behavior with the tooltip arrow bug and the minified Foundation css v6.2.1. Using the unminified css seems to fix the problem.

**Comment by tinyfly** [comment]
@gakimball I can provide some details.

Here is the working css (un-minified version) for the arrow:

```css
.tooltip::before {
  content: '';
  display: block;
  width: 0;
  height: 0;
  border: inset 0.75rem;
  border-color: transparent transparent #0a0a0a;
  border-bottom-style: solid;
  border-top-width: 0;
  bottom: 100%;
  position: absolute;
  left: 50%;
  -webkit-transform: translateX(-50%);
  -ms-transform: translateX(-50%);
  transform: translateX(-50%);
}
```

Here is the broken css (minified version):

```css
.tooltip.top:before, .tooltip:before {
  content: '';
  display: block;
  width: 0;
  height: 0;
  border: .75rem inset;
}

.tooltip:before {
  border-color: transparent transparent #0a0a0a;
  border-bottom-style: solid;
  border-top-width: 0;
  bottom: 100%;
  position: absolute;
  left: 50%;
  -webkit-transform: translateX(-50%);
  transform: translateX(-50%);
}
