### ISSUE TITLE
[Request] placeholder color, crumb-slash and other feautres

### ISSUE THREAD

**Issue by SalahAdDin** [zurb/foundation-sites#8104]
What's about this features? Were in Foundation 5.4 and are very useful. Now i don't know how replace it.

OK, prefix and postfix isn't matter but what's about placeholder styles? I want put $oil as placeholder color but i can't do it:
```scss
::-webkit-input-placeholder {
      color: $input-placeholder-font-color;
    }

    :-moz-placeholder { /* Firefox 18- */
       color: $input-placeholder-font-color;  
    }

    ::-moz-placeholder {  /* Firefox 19+ */
       color: $input-placeholder-font-color;  
    }

    :-ms-input-placeholder {  
       color: $input-placeholder-font-color;  
    }
```

And this:
```html
<nav class="top-bar" data-topbar role="navigation"
         data-options="is_hover: false;
         sticky_on: large;
         custom_back_text: true;
         back_text: &laquo; {% trans 'back' %};
         mobile_show_parent_link: false;">
```
