### ISSUE TITLE
class="row column" and mixin grid-column-row() have different output

### ISSUE THREAD

**Issue by LichtAnd** [zurb/foundation-sites#8108]
When using class="row column" on multiple consequent elements everything is as expected.

HTML:
```html
<div class="row column">correct full-width div<div>
<div class="row column">correct full-width div<div>
```

When I use class="example" on the same elemnts as before and the grid-column-row mixin on the example class the last element gets a float:right.

SCSS:
```css
.example {
	@include grid-col-row();
}
```

HTML:
```html
<div class="example">example text<div>
<div class="example">this one gets float right<div>
```

When I inspect in dev tool it says: 
```scss
.example:last-child:not(:first-child) {float: right;}
```
but I dont get why?

**Comment by gakimball** [comment]
You're right, that style shouldn't be applying. Column rows have no float, instead using the auto margins of the `.row` class to center themselves.

**Comment by flyingL123** [comment]
Just came across this after posting a similar question here: http://stackoverflow.com/questions/36436019/zurb-foundation-6-using-grid-column-row-mixin

Any idea if this is going to be updated?

**Comment by alexbarrett** [comment]
Just ran into this myself.

The problem is that [_classes.scss](https://github.com/zurb/foundation-sites/blob/35237f086db0a2b586574c95d1d1237970454acb/scss/grid/_classes.scss#L68) contains the following style definition:

```css
  // Column row
  // The double .row class is needed to bump up the specificity
  .#{$column}.#{$row}.#{$row} {
    float: none;

    // To properly nest a column row, padding and margin is removed
    .#{$row} & {
      padding-left: 0;
      padding-right: 0;
      margin-left: 0;
      margin-right: 0;
    }
  }
```

However these same styles are not applied when using the `@grid-column-row` row mixin.
