### ISSUE TITLE
[Feature][Breadcrumb] Use $bread-crumb-slash settings

### ISSUE THREAD

**Issue by SalahAdDin** [zurb/foundation-sites#8131]
I have using the last feature $crumb-slash and i can't find in the new Foundation version. 

This option is very useful if we want customizing a lot the breadcrumbs:
![seleccion_084](https://cloud.githubusercontent.com/assets/5034215/12957809/a3e9b18a-cffc-11e5-86ce-6ffea51fa0b2.png) 

We have to this:
![seleccion_106](https://cloud.githubusercontent.com/assets/5034215/13022173/9e19e178-d1ad-11e5-9a00-259b7b85a843.png)

I think that this feature will be useful for us, i want implements it but i don't understand the code:

``` scss
@if $breadcrumbs-item-slash {
      // Need to escape the backslash
      $slash: if($global-text-direction == 'ltr', '/', '\\');

      &:not(:last-child)::after {
        color: $medium-gray;
        content: $slash;
        margin: 0 $breadcrumbs-item-margin;
        position: relative;
        top: 1px;
        opacity: 1;
      }
    }
```

This is the actual code.

``` scss
&:before {
    color: $crumb-slash-color;
    content: "#{$crumb-slash}";
    margin: 0 $crumb-side-padding;
    position: relative;
    top: 1px;
  }
```

And this is the old code for it.

Can you hang back this feature for the new version?
