### ISSUE TITLE
Problem with clearfix in flexbox 

### ISSUE THREAD

**Issue by maggo** [zurb/foundation-sites#8148]
When using the clearfix mixin on an element with ``display: flex;`` you get a small 1px border left and right in Safari and Chrome.

The problem is [documented here](http://danisadesigner.com/blog/flexbox-clear-fix-pseudo-elements/) with a nice fix:

```css
.clear-fix:before,
.clear-fix:after {
  flex-basis: 0;
  order: 1;
}
```

Adding those two lines to [the mixin](https://github.com/zurb/foundation-sites/blob/develop/scss/util/_mixins.scss#L135) will fix the issue without harming current usage in non-flexbox layouts and only add a few lines to the compiled css.
