### ISSUE TITLE
Top Menu isn't easy to adapt.

### ISSUE THREAD

**Issue by SalahAdDin** [zurb/foundation-sites#8181]
Hi, i have problems to adapt my top-bar menu to new system:
![seleccion_140](https://cloud.githubusercontent.com/assets/5034215/13097883/18a04fc0-d4f3-11e5-81da-6ce93ebc106c.png)

I have now this;
![seleccion_138](https://cloud.githubusercontent.com/assets/5034215/13097890/21d56d1e-d4f3-11e5-9378-da405e3fe442.png)
I couldn't put the image over top menu, put `position: relative` don't works, put absolute make that left menu bar go to left side.
![seleccion_142](https://cloud.githubusercontent.com/assets/5034215/13098178/c7fffc98-d4f5-11e5-88b2-e305732bfa25.png)
I can't delete these "margin-right" fake from image.

I have a anoying bug in right side menú:
![seleccion_141](https://cloud.githubusercontent.com/assets/5034215/13098073/cd635406-d4f4-11e5-8072-a99ab42031a0.png)
 How can i  delete the "padding-bottom" from these object? Anyone of internal objects have padding, only `top-bar-right` classed object.

And when change drilldownmenu by dropdown menu is a bad idea:
![seleccion_136](https://cloud.githubusercontent.com/assets/5034215/13098228/0ec48c0c-d4f6-11e5-953d-e95a24f75bfb.png)
![seleccion_134](https://cloud.githubusercontent.com/assets/5034215/13098233/15539ca2-d4f6-11e5-9200-660e9c72954f.png)

As you can see, if we put many options in the menu they go aside to the canvas and generate a gap, right gap in responsive mode.

![seleccion_076](https://cloud.githubusercontent.com/assets/5034215/13098252/3893e3f2-d4f6-11e5-8207-6bd60eb2ff26.png)
But with old responsive version we have a drilldown menu that adapt vertically give a beautiful view.

![seleccion_144](https://cloud.githubusercontent.com/assets/5034215/13098395/2ae3de28-d4f7-11e5-9587-017836c4139a.png)
This is a performance in Opera/Chromium.

![seleccion_143](https://cloud.githubusercontent.com/assets/5034215/13098401/35e46aae-d4f7-11e5-84d1-e9c67a5e9269.png)
And this, Firefox.

Can you see something wrong? In Firefox top-bar-right put automatically the widht adjust to select container, but, in Opera/Chromiun... they couldn't.

Is there one way to put in Foundation 6 the old top-bar menu version?
The other object i could adapt to Foundation 6, but Top Bar menu i couldn't yet.

This is my scss code:
```scss
 > div:last-child {
    background: rgba(189, 4, 12, .5);
    nav {
      > ul:first-child {
        /*img {
          margin-top: rem-calc(-80);
          width: rem-calc(160);
          z-index: 10;
        }*/
        > li:last-child {
          z-index: 10;
          width: 85%;
          margin-top: rem-calc(-72);
        }
      }
    }
    section {
      margin-top: rem-calc(5);
    }
  }
  .top-bar {
    select {
      background: $red-wine;
      border-color: $red-wine;
      color: white;
      &:hover {
        border-color: $red-wine;
      }
    }
    .top-bar-title {
      margin-right: 0;
      margin-left: 0;
    }
  }
```

And this is my html code:
```html
<nav class="top-bar row" role="navigation">
    <ul class="top-bar-title">
        <li class="title-bar menu" data-responsive-toggle="responsive-menu" data-hide-for="medium">
            <button class="menu-icon" type="button" data-toggle></button>
            <div class="title-bar-title">{% trans 'Menu' %}</div>
            <h1 class="hide-for-medium"><a href="{% pageurl site_root %}">{{ site_name }}</a></h1>
        </li>
        <li class="menu-text menu">
            <a href="{% pageurl site_root %}" role="button">
                <img src="{% static 'dist/img/Logo_CCCT2.jpg' %}" class="thumbnail show-for-medium">
            </a>
        </li>
    </ul>
    <section class="" id="responsive-menu">
        <ul class="top-bar-left dropdown menu" data-dropdown-menu>
            {% for menuitem in menuitems %}
                <li>
                    {% if menuitem.show_dropdown %}
                        <a href="#">{{ menuitem.title }}</a>
                        {% top_menu_children parent=menuitem %}
                    {% else %}
                        <a href="{% pageurl menuitem %}">{{ menuitem.title }}</a>
                    {% endif %}
                </li>
            {% endfor %}
        </ul>

        <ul class="top-bar-right">
            <li class="menu">
                <form action="{% url 'set_language' %}" method="post">
                    {% csrf_token %}
                    <div class="input-group">
                        <input name="next" type="hidden" value="{{ redirect_to }}"/>
                        <select name="{% trans 'language' %}" class="input-group-field">
                            {% get_current_language as LANGUAGE_CODE %}
                            {% get_available_languages as LANGUAGES %}
                            {% get_language_info_list for LANGUAGES as languages %}
                            {% for language in languages %}
                                <option value="{{ language.code }}"
                                        {% if language.code == LANGUAGE_CODE %} selected="selected" {% endif %}>
                                    {{ language.name_local }} ({{ language.code }})
                                </option>
                            {% endfor %}
                        </select>
                        <div class="input-group-button">
                            <input class="button radius alert" type="submit" value="{% trans 'Go' %}"/>
                        </div>
                    </div>
                </form>
            </li>
        </ul>
    </section>
</nav>
```

I think that old version have many options, for hover states, for active state and so..

Thank you very much man.
