### ISSUE TITLE
[Typography] h1-h6 Font Mixins

### ISSUE THREAD

**Issue by andycochran** [zurb/foundation-sites#8252]
Currently, `_base.scss` declares all the `_settings.scss` variables (except for `$header-sizes`) directly in an `h1`-`h6` rule-set. The responsive sizes are then declared separately in an `@each` loop. It would be nice if this was done with mixins so that you could style any element to match the responsive style of a particular heading.

For example… 
```scss
.module {
  @include heading-2; 
}
```
would compile to… 
```scss
.module {
  font-family: "Helvetica Neue", Helvetica, Roboto, Arial, sans-serif;
  font-weight: normal;
  font-style: normal;
  color: inherit;
  text-rendering: optimizeLegibility;
  margin-top: 0;
  margin-bottom: 0.5rem;
  line-height: 1.4; }
  .module small {
    color: #cacaca;
    line-height: 0; }
.module {
  font-size: 1.25rem; }
@media screen and (min-width: 40em) {
  .module {
    font-size: 2.5rem; }}
```

:+1::-1:? I can PR.
