### ISSUE TITLE
[DropdownMenu] data-hover-delay ignored on submenu

### ISSUE THREAD

**Issue by designerno1** [zurb/foundation-sites#8316]
**How can we reproduce this bug?**
set data-hover-delay to something great 500

**What did you expect to happen?**
got a submenu with 2 submenus hover over the first submenu the submenu opens immediately
i expected the submenu to wait the amount of time to open in delay given

hover the second submenu the submenu opens immediately but the first waits time x to close

**Comment by designerno1** [comment]
i think it comes from the
```scss
// [TODO] Cut back specificity
    // scss-lint:disable SelectorDepth
    &:not(.js-dropdown-nohover) > .is-dropdown-submenu-parent:hover > &,
    &.js-dropdown-active {
      display: block;
    }
```
because this adds a display block on the css event hover and displays the submenu immediately

adding a .no-js could bei the solution

```scss
// [TODO] Cut back specificity
    // scss-lint:disable SelectorDepth
    .no-js &:not(.js-dropdown-nohover) > .is-dropdown-submenu-parent:hover > &,
    &.js-dropdown-active {
      display: block;
    }
```
