### ISSUE TITLE
No $global-radius applied to accordion-title on hover. Here's my solution

### ISSUE THREAD

**Issue by iamtirado** [zurb/foundation-sites#8322]
**How can we reproduce this bug?**
Note: Working with foundation sass.
1. Apply a noticeable global radius.
2. Place accordion with title in template.
3. Hover over title.

**What did you expect to happen?**
Hover background color to have global radius applied.

**What happened instead?**
Hover background color has no global radius applied.
**Test case:**

To solve the issue, I added a line of code to 
`components/_accordion.scss `
at bottom of accordion-title mixin like so:

```scss
@mixin accordion-title {
  display: block;
  padding: $accordion-item-padding;
  line-height: 1;
  font-size: rem-calc(12);
  color: $accordion-item-color;
  position: relative;
  border-bottom: $accordion-content-border;
  border-radius: $global-radius; // I ADDED THIS LINE
}
```

That may not be the solution. i realized it needs to lose the global radius at bottom when expanded.
