### ISSUE TITLE
No $global-radius applied to accordion-title on hover. Here's my solution

### ISSUE THREAD

**Issue by iamtirado** [zurb/foundation-sites#8323]
**How can we reproduce this bug?**
Note: Working with foundation sass.
1. Apply a noticeable global radius.
2. Place accordion with title in template.
3. Hover over title.

**What did you expect to happen?**
Hover background color to have global radius applied.

**What happened instead?**
Hover background color has no global radius applied.
**Test case:**

To solve the issue, I added a few lines of code to 
`components/_accordion.scss `
at bottom of accordion-title mixin like so:

```scss
@mixin accordion-title {
  display: block;
  padding: $accordion-item-padding;
  line-height: 1;
  font-size: rem-calc(12);
  color: $accordion-item-color;
  position: relative;
  border-bottom: $accordion-content-border;

// MY CODE BELOW
  &[aria-expanded='false'] {
    border-radius: $global-radius;
  }
  &[aria-expanded='true'] {
    border-radius: $global-radius $global-radius 0 0;
  }
// MY CODE ABOVE
  &:hover,
  &:focus {
    background-color: $accordion-item-background-hover;
  }
  @if $accordion-plusminus {
    &::before {
      content: "+";
      position: absolute;
      #{$global-right}: 1rem;
      top: 50%;
      margin-top: -0.5rem;
    }
    .is-active > &::before {
      content: "–";
    }
  }
}

```
You may find have a better way to implement this, but 'ere ya go.
