### ISSUE TITLE
Flexordering not implemented correctly

### ISSUE THREAD

**Issue by DaSchTour** [zurb/foundation-sites#8360]
**How can we reproduce this bug?**

Use .small for a column element

**What did you expect to happen?**

Element is given a flex-order.

**What happened instead?**

.small should not add order

**Further description**
I had an element with class .small for smaller text and wondered why it is not in the right place in my row and saw, that there are a lot of classes with flex order.

```css
.small {
  -webkit-order: 1;
      -ms-flex-order: 1;
          order: 1; }

.small {
  -webkit-order: 2;
      -ms-flex-order: 2;
          order: 2; }

.small {
  -webkit-order: 3;
      -ms-flex-order: 3;
          order: 3; }


.small {
  -webkit-order: 4;
      -ms-flex-order: 4;
          order: 4; }

.small {
  -webkit-order: 5;
      -ms-flex-order: 5;
          order: 5; }


.small {
  -webkit-order: 6;
      -ms-flex-order: 6;
          order: 6; }
```

I guess there went something wrong in flex.scss with this function

```scss
@include -zf-each-breakpoint {
    @for $i from 1 through 6 {
      .#{$-zf-size} {
        @include flex-order($i);
      }
    }
  }
```

I think it should look like this

```scss
@include -zf-each-breakpoint {
    @for $i from 1 through 6 {
      .#{$-zf-size}-order-#{$i} {
        @include flex-order($i);
      }
    }
  }
```
