### ISSUE TITLE
Pagination contain weird characters (Â» and Â«)

### ISSUE THREAD

**Issue by ve3** [zurb/foundation-sites#8374]
I was download Foundation from download page Complete section.
Look into the file foundation.min.css
These classes.
```css
.pagination-previous.disabled::before, .pagination-previous a::before{
    content: "Â«";
}
.pagination-next.disabled::after, .pagination-next a::after{
    content: "Â»";
}
```
It contain some weird characters which is not exists in foundation.css (non-minified). Are your minifier have some problem or something?
