### ISSUE TITLE
Hollow dropdown buttons show white "triangle" instead of button color

### ISSUE THREAD

**Issue by pdrlps** [zurb/foundation-sites#8404]
Hi guys!

I'm not sure if this is expected behaviour, but if we combine the "dropdown" and "hollow" classes in a button, the dropdown triangle keeps the default colour. I think it should be displayed in the button color instead (success, secondary...). Without changes, default hollow dropdown buttons have an "invisible" triangle.

**How can we reproduce this bug?**
1. Create dropdown button (classes "button dropdown hollow").

**What did you expect to happen?**

The dropdown triangle should be the same highlight color as the button.

**What happened instead?**

The dropdown triangle keeps the default color (white = invisible).

**Test case:**

http://codepen.io/anon/pen/vGXzMz

**Comment by stefan2** [comment]
For a quick hack change condition in [Line 244](https://github.com/zurb/foundation-sites/blob/v6.2.0/scss/components/_button.scss#L244)

from
```
@if $button-fill == hollow {
```
to
```
@if $button-fill != hollow {
```

The condition sounds confusing because `$button-fill` should be `hollow` at
this point (this condition). Anyways, this follows the same logic as seen in line [221](https://github.com/zurb/foundation-sites/blob/v6.2.0/scss/components/_button.scss#L221) (vs. [Line 204](https://github.com/zurb/foundation-sites/blob/v6.2.0/scss/components/_button.scss#L204)?). The "hollow" needs a further investigation

**Comment by berzley** [comment]
I fixed this in one of my projects with the following change on [Line 220](https://github.com/zurb/foundation-sites/blob/v6.2.0/scss/components/_button.scss#L220)

```SCSS
    // Hollow style
    @if $button-fill != hollow {
      &.hollow {
        @include button-hollow;
        @include button-hollow-style;

        &.dropdown {
          @include button-dropdown;
            &::after {
            border-top-color: $button-background;
          }
        }

        @each $name, $color in $foundation-palette {
          &.#{$name} {
            @include button-hollow-style($color);

            &.dropdown {
              @include button-dropdown;
                &::after {
                border-top-color: $color;
              }
            }
          }
        }

      }
    }
```

I'm sure there's a more optimized way to write it but it works and I've moved on.
