### ISSUE TITLE
Feature request - float classes

### ISSUE THREAD

**Issue by MkBeeCtrl** [zurb/foundation-sites#8494]
Sorry for posting here, I my defend I'd like to say I have no idea where I should submit such a request.

What do you think about expanding float classes like:

.float-left or .float-right

to a little bit more advanced like .large-float-left .medium-float-right ?

**Comment by ncoden** [comment]
Hi.

You are is the right place to submit features requests. I wish Foundation maintainers would be more active ;).

If we could, we would maked responsive all the Foundation classes. It's really usefull to give a particular behavior to a component for a particular device. But we have to care about the generated file size, and responsive classes take lot of place (the classes content is duplicated for each breakpoint). So we only make responsive the most used classes, like `visible`.

Can a Yetinaute say if `.*-float-{left,right}` would be very used ? (poke @kball, @colin-marshall)

You can always add this classes by yourself in your project. I can generate it for you if you don't know how.

**Comment by Nikolaus91** [comment]
Thanks for quick response!

I do know how to add them by myself and that's why I wanted to share :) but thanks that you wanted to help. It's always appreciated. 

I can describe shortly few possible scenarios when a developer could be using such classes if you wish.

True about the file size. 

While writing this post I something came up on my mind. Will try to set the codepen for a better view.

Dnia 01.04.2016 o godz. 03:07 Nicolas Coden <notifications@github.com> napisał(a):

**Comment by ncoden** [comment]
Here the float classes in Scss : https://gist.github.com/ncoden/469cdf561f6c6ec012b15f30193b7fc5
And in CSS : https://gist.github.com/ncoden/db5fb1a26bd2aed764fe7c859adff17d

I'm assuming you use a build tool.
Move this code in a new `foundation-float.css` and import this file in your `<head>`

**Comment by kball** [comment]
Hi @Nikolaus91 

Being able to implement things in a responsive way like this without bloating the core framework is one of the reasons why many/most of our classes are implemented as sass methods that can be included.  For example see the way grid columns are implemented in scss/grid/_column.scss

`.float-left` and `.float-right` are not currently implemented in this way, but I would happily consider a pull request that moved them to this approach for v6.3.0

**Comment by Nikolaus91** [comment]
@kball you mean to create for example a file _responsive_float.scss in 6.3.0 if I understan you correctly so the user can add it to core?

Sounds well, I would be happy if I can contribute some code to help you guys. I never did so. Can I contribute?

**Comment by andycochran** [comment]
You could just include this in your app: 

```scss
.float-left { float: left; }
.float-right { float: right; }
.float-none { float: none; }
@include breakpoint(medium) {
  .medium-float-left { float: left; }
  .medium-float-right { float: right; }
  .medium-float-none { float: none; }
}
@include breakpoint(large) {
  .large-float-left { float: left; }
  .large-float-right { float: right; }
  .large-float-none { float: none; }
}
```
