### ISSUE TITLE
Hidden .tabs-panel with equalizer

### ISSUE THREAD

**Issue by JTallis** [zurb/foundation-sites#8556]
Equalizer sets all heights to 0 when it's in a `.tabs-panel` that is hidden.

I'm certain that this doesn't happen in F5 as it was working fine until upgrading to F6 and changing the HTML so that it matches that of F6.

Here is an: [example](http://codepen.io/anon/pen/groKXO)

Click the Equalizer tab and you will see that all heights will be 0 until you resize the browser and only then will it re-equalize and be the right heights.

Is this a bug? Does anyone have any suggestions on how to fix this?

**Comment by designerno1** [comment]
quick and dirty fix you can try something like this
```js
$('[data-tabs]').on('change.zf.tabs', function(e, $target) {
  var $tabsEq = $('[data-tabs-content=' + $target.parent('[data-tabs]').attr('id') + '] > .tabs-panel:eq(' + $target.index() + ') > [data-equalizer]');
  if ($tabsEq.length) {
    $tabsEq.data('zfPlugin')._reflow();
  };
});
```

**Comment by andycochran** [comment]
Just works if you add this: 

```scss 
.tabs-panel {
  display: block;
  height: 0;
  overflow: hidden;
  padding: 0;
}

.tabs-panel.is-active {
  height: auto;
  padding: 1rem;
}
```
Maybe `display:none` is the wrong way to go for tabs?
