### ISSUE TITLE
.menu-icon CSS isn't in complete or custom downloads

### ISSUE THREAD

**Issue by JTallis** [zurb/foundation-sites#8565]
Half of the `.menu-icon` CSS is not present in complete or custom downloads of Foundation. 

The available CSS that comes with the downloads is for `.menu-icon.dark`. The CSS that is missing is:

```css
.menu-icon {
  position: relative;
  display: inline-block;
  vertical-align: middle;
  cursor: pointer;
  width: 20px;
  height: 16px; }
  .menu-icon::after {
    content: '';
    position: absolute;
    display: block;
    width: 100%;
    height: 2px;
    background: #fefefe;
    top: 0;
    left: 0;
    box-shadow: 0 7px 0 #fefefe, 0 14px 0 #fefefe; }
  .menu-icon:hover::after {
    background: #cacaca;
    box-shadow: 0 7px 0 #cacaca, 0 14px 0 #cacaca; }
```
