### ISSUE TITLE
[Media Object] margin bottom within Callout

### ISSUE THREAD

**Issue by andycochran** [zurb/foundation-sites#8604]
In order to keep the padding even on all four sides of a Callout, the last child has its bottom margin removed. But if that last item is a Media Object, the margin only gets partially removed, 'cause a Media Object's bottom margin is actually a combination of the Media Object's margin plus the last item's margin in tallest `.media-object-section`. 

What does everyone think about this? 
```scss
.media-object-section > :last-child {
  margin-bottom: 0;
}
```

Here's a pen showing the issue and fix: 
http://codepen.io/andycochran/pen/aNYRJW
