### ISSUE TITLE
[Accordion] `$accordion-content-color` is defined but never used

### ISSUE THREAD

**Issue by deepfriedmind** [zurb/foundation-sites#8641]
It seems the variable `$accordion-content-color` isn't used anywhere throughout Foundation 6.2.1, so changing it in the settings doesn't actually do anything.

**Comment by denisahac** [comment]
Yes you're right. Upon checking the foundation [accordion](https://github.com/zurb/foundation-sites/blob/develop/scss/components/_accordion.scss) component the `$accordion-content-color` variable on line number 39 isn't used anywhere in the file. 

Based on the name of the variable, it should be a declaration inside the accordion-content mixin

```CSS
@mixin accordion-content {
  /* Append declaration */
 color: $accordion-content-color;
}
```
