### ISSUE TITLE
Foundation grid centering fails on .column:last-child

### ISSUE THREAD

**Issue by rediris** [zurb/foundation-sites#8653]
**How can we reproduce this bug?**
Using `large-centered` or `medium-centered` on `columns`:

```
<section class="wrapper">
  <div class="row">
    <div class="columns medium-6 large-8 large-centered">
      <div class="panel panel-1">
        <p>Should be a centered div on large screens, which it is.</p>
      </div>
    </div>
    <div class="columns medium-6 large-8 large-centered">
      <div class="panel panel-2">
        <p>Should be a centered div on large screens, but it isn't, because of this:</p>
        <code>
          .column:last-child:not(:first-child),
          .columns:last-child:not(:first-child) {
            float: right;
          }
        </code>
        <p>Alas, the last column child doesn't get the love.</p>
        <p>Note: this was not an issue in Foundation < 6.
    </div>
</section>
```

**What did you expect to happen?**
Each `column` with a `*-centered` class applied should be centered.
**What happened instead?**
The `:last-child` floated right instead.
**Test case:**
Observe and weep:
- [CodePen with Foundation 6](http://codepen.io/rediris/pen/rerGgO)

**Comment by andycochran** [comment]
This is a specificity issue. 

This:
```scss
.columns:last-child:not(:first-child) {
  float: right;
}
```
trumps this: 
```scss
.columns.large-centered {
  float: none;
  margin-left: auto;
  margin-right: auto;
}
```

We don't wanna do something as crude as `float: none !important;` (although it'd work). I think the fix here might be to make the last-child class even more specific: 

```scss
// Last column alignment
@if $grid-column-align-edge {
  @each $size, $value in $breakpoint-classes {
    &:last-child:not(:first-child):not(.#{$size}-centered) {
      float: $global-right;
    }
  }
}
```
