### ISSUE TITLE
Hidden elements are visible in block grid

### ISSUE THREAD

**Issue by BenMorel** [zurb/foundation-sites#8694]
I want to display only the first items of a long block grid, hiding the rest of the items until a button is clicked:

``` html
<ul class="small-block-grid-2">
    <li>...</li>
    <li>...</li>
    <li>...</li>
    <li>...</li>
    <li hidden>...</li>
    <li hidden>...</li>
    <li hidden>...</li>
    <li hidden>...</li>
</ul>
```

The user agent's default stylesheet, as well as normalize.css, have a rule such as:

``` css
[hidden] {
    display: none;
}
```

It is, however, overridden by Foundation:

``` css
[class*="block-grid-"] > li {
    display: block;
}
```

The end result is, **`hidden` elements are visible**.

Would you consider changing the rule to something like:

``` css
[class*="block-grid-"] > li:not([hidden]) {
    display: block;
}
```

This could also be extended to the block grid's `<ul>`, and probably to other Foundation components.

**Comment by BenMorel** [comment]
Note: in the meantime, an easy fix is to override in turn Foundation in the website's stylesheet:

```css
[class*="block-grid-"] > li[hidden] {
    display: none;
}
```

**Comment by denisahac** [comment]
Why not attach a `.hide` class in the `li` elements. And you don't need to worry about writing your overrides.

**Comment by BenMorel** [comment]
@denisahac `hidden` is not just a CSS rule, it has a [semantic meaning](https://davidwalsh.name/html5-hidden)!

**Comment by andycochran** [comment]
I think the fix is to add `[hidden]` to the Visibility Classes: 

```scss
// Basic hiding classes
.hide, [hidden] {
  display: none !important;
}
```
