### ISSUE TITLE
Issue with nested rows in collapsed parent

### ISSUE THREAD

**Issue by saadshahd** [zurb/foundation-sites#8915]
Hi,

There's an issue with these rules:
```CSS
.row .row {
  margin-right: $negative-gutter;
  margin-left: $negative-gutter;
}
```
Which undo the gutters of the nested row's parent column. But in this scenario:
```CSS
.row.collapse
  .columns
    .row
```
It causes an issue, because the parent column here doesn't have gutters. So I tried to fix it here #8853.
By adding this new rules:
```CSS
.row.collapse > .column > .row {
  margin-left: 0;
  margin-right: 0;
}
```
But the issue remains for scenarios like here http://codepen.io/SaadShahd/pen/zBvXXr?editors=1100

So I added to my codebase a modifier class and it determines when the row is a child of a collapsed row.
