### ISSUE TITLE
[Foundation for Sites] grid-col mixin - Set gutters on small and reset on above breakpoints

### ISSUE THREAD

**Issue by danielnass** [zurb/foundation-sites#8924]
Hi guys!

I want to set gutters on small breakpoint and remove them in above breakpoints.

If I use normal classes, everything works fine like we can see in follow CodePen: [http://codepen.io/danielnass/pen/wWMYoQ](http://codepen.io/danielnass/pen/wWMYoQ)

BUT, if I use a grid-col mixin, them padding will not be 'reseted', and medium breakpoint assume gutter from small breakpoint. The gutter '0' will never be setted.

My actual scss:

``` scss
.video {
    @include grid-col(12);

    @include breakpoint(medium) {
        @include grid-col(8,0);
    }
}

.title {
    @include grid-col(12);

    @include breakpoint(medium) {
        @include grid-col(4,0);
    }
}
```

I found where this happens, is in line 74 of _columns.scss. This assume you never want to pass a zero gutter in breakpoint above small.

``` scss
@mixin grid-column(
  $columns: $grid-column-count,
  $gutter: $grid-column-gutter
) {
  @include grid-column-size($columns);
  float: $global-left;

  // Gutters
  @if type-of($gutter) == 'map' {
    @each $breakpoint, $value in $gutter {
      $padding: rem-calc($value) / 2;

      @include breakpoint($breakpoint) {
        padding-left: $padding;
        padding-right: $padding;
      }
    }
  }
  @else if type-of($gutter) == 'number' and strip-unit($gutter) > 0 {
    $padding: rem-calc($gutter) / 2;
    padding-left: $padding;
    padding-right: $padding;
  }

  // Last column alignment
  @if $grid-column-align-edge {
    &:last-child:not(:first-child) {
      float: $global-right;
    }
  }
}
```

To resolve this issue, we just need to verify if gutter is better or equal 0.

``` scss
  @else if type-of($gutter) == 'number' and strip-unit($gutter) > 0 {
```

to

``` scss
  @else if type-of($gutter) == 'number' and strip-unit($gutter) >= 0 {
```

If community judge this is a real issue, I will provide a PR :)
Thanks a lot!
