### ISSUE TITLE
v6.2.3 - .top-bar-title strong is missing styling

### ISSUE THREAD

**Issue by JTallis** [zurb/foundation-sites#9029]
I'm not sure if this was intended or not but I have spotted a slight styling issue when it comes to `.top-bar-title strong`. I copied and pasted the code from the documentation (Top Bar, Advanced Layout) into a codepen so you can see the issue with the title.

[http://codepen.io/JLT93/pen/ZOvdpG](http://codepen.io/JLT93/pen/ZOvdpG)

Shouldn't there already be appropriate styling for the whole title bar?

**Comment by mattferderer** [comment]
It appears this is a case of doc specific styling. Here is what they're adding that you could borrow:

```scss
.docs-code-live .top-bar-title strong {
  margin-top: 7px;
  display: inline-block;
  margin-left: 8px;
}
```

I'll try adding a pull request to see if making that addition would be acceptable.
