### ISSUE TITLE
grid-row mixin with ONLY collapse behaviour does not work

### ISSUE THREAD

**Issue by samuells** [zurb/foundation-sites#9082]
The mixin `grid-row` should accept `behaviour: collapse` according to the documentation from _row.scss. 

> @param {Keywords} $behavior [null]
>   Modifications to the default grid styles. `nest` indicates the row will be placed inside another row. `collapse` indicates that the columns inside this row will not have padding. `nest collapse` combines both behaviors.

But it isn't working because of the wrong if condition (I assume) and currently collapsed behaviour works only in combination with `nest` value.
```
@if index($behavior, nest) != null {
    @include grid-row-nest($gutter);

    @if index($behavior, collapse) != null {
      margin-left: 0;
      margin-right: 0;
    }
  }
  @else {
    max-width: $width;
    margin-left: auto;
    margin-right: auto;
  }
```

**How can we reproduce this bug?**

use : `@include grid-row($behavior: collapse);`

**What did you expect to happen?**

I expect **unset** `max-width` and: 
```
margin-left: 0;
margin-right: 0;
```

**What happened instead?**
```
max-width: $width;
margin-left: auto;
margin-right: auto;
```

**Comment by kball** [comment]
@andycochran or @ncoden can one of you take a look at this?

**Comment by ncoden** [comment]
Hmm... I'm not sure (because in fact I don't like the way we handle columns margins), but I think @samuells is right.

**Comment by ncoden** [comment]
We should have:
```scss
  @if index($behavior, nest) != null {
    @include grid-row-nest($gutters);
  }
  @else {
    @include grid-row-size($size);
  }

  @if or index($behavior, nest) != null index($behavior, collapse) != null {
    margin-right: 0;
    margin-left: 0;
  }
  @else {
    margin-right: auto;
    margin-left: auto;
  }
```

But there is probably a way to implement it better than this.
