### ISSUE TITLE
Combined column/row size relative to container instead of a regular row

### ISSUE THREAD

**Issue by rafalages** [zurb/foundation-sites#9234]
According to documentation, I would get the same width of these two medium-6 divs:

``` html
<body>
  <div class="row">
    <div class="column medium-6 medium-centered">
       [CONTENT]
    </div>
  </div>
</body>
```

and

``` html
<body>
  <div class="row column medium-6">
    [CONTENT]
  </div>
</body>
```

But what I've noticed is the second one have a _width 50%_ of _body_, and the first, from _.row_

**Sugested fix**
Set max-width of .row.column calculated based on _columns_ and _$global-width_ instead of just _$global-width_
In `https://github.com/zurb/foundation-sites/blob/develop/scss/grid/_column.scss`

``` scss
@mixin grid-column-row(
  $columns: null,
  $gutter: $grid-column-gutter,
) {
  @include grid-row;
  @include grid-column($gutter: $gutter);

 // MY FIX
   @if $columns != null {
    max-width: calc(#{$columns} / #{$grid-column-count} * #{$global-width});
  }

  &,
  &:last-child {
    float: none;
  }
}
```

**Link with the problem and my suggested fix**
http://codepen.io/Rafalages/pen/YGYkRx
