### ISSUE TITLE
Feature request: visibility class conjunctions

### ISSUE THREAD

**Issue by paxperscientiam** [zurb/foundation-sites#9326]
Hey y'all,

Include (s)css that allows for the conjunction of visibility classes.

That is, let's say the user wants an element to show only when the device is in portrait orientation AND "small or medium".

````scss
   @media screen and #{breakpoint(medium down)} and #{breakpoint(portrait)} {
    .show-for-medium-portrait {
      display: block !important;
      }
}
````
The above works, though, from what I can tell, the code must come after default visibility classes.

Thoughts?
