### ISSUE TITLE
[Input Group] Flex-mode input group input height does not match non-input-group inputs

### ISSUE THREAD

**Issue by simshaun** [zurb/foundation-sites#9344]
Foundation 6.2.4

I'm being pedantic...

An input-group input's height does not match up with non-input-group inputs when displayed side-by-side as in the demo. It's off by a few pixels.

**Demo:**

http://simshaun-static.s3-website-us-east-1.amazonaws.com/foundation/6.2.4/

**Example:**

![image](https://cloud.githubusercontent.com/assets/379519/20080946/887026fc-a51a-11e6-9db1-8661ca3425b3.png)

Removing `height: auto` on `.input-group-field` solves the problem, but I don't know if that causes issues elsewhere or if it causes problems in non-flex mode.

**Comment by glen-84** [comment]
I'm going to use this for now:

```scss
.input-group-field {
    height: ($input-font-size + ($form-spacing * 1.5) - rem-calc(1));
}
```

I'm not sure why Foundation uses explicit heights for text inputs.
