### ISSUE TITLE
[Feature] Classes and mixins for Header styles

### ISSUE THREAD

**Issue by ncoden** [zurb/foundation-sites#9483]
- Add a mixin to generate custom Header styles...
- Add classes for the default headers, like `.h1`, `.h2`, `.h3`...

**Comment by ncoden** [comment]
Hum... I taked a look at typography, and I think it needs a big refactor:
- Reset and features are mixed.
- There is no one single `@mixin`.
- Everything is mixed in one big file, not organized by components.
- Config variables uses too common names and need a namespace.

About `$header-styles`:
- It is a map of properties for each header for each breakpoint (_breakpoint_ > _header_ > _properties_)
- It does not have value units and should apply them automatically
- It should apply default properties.

So I have several suggestions to factorize and simplify stuff:
**1/** For default properties, it should be applied _before_ we process the styles map, with a base mixin or placeholder for all headers, not here.

**2/** We can sort `$header-styles` by _name_ then _breakpoint_ (_header_ > _breakpoint_ > _properties_) to have a _component_ approach, and provide a mixin to generate single responsive and non-responsive headers.
```scss
// Generate styles for a header
@mixin header-style ($properties) { // ideally zf-header--style
   ... // like in scss/typography/_base.scss:330
}

// Generate header styles for each breakpoint in $map
@mixin header-responsive-style ($map) { // ideally zf-header-responsive--style
    @each $bp, $v in $map {
        @include breakpoint($bp) {
            @include header-size($v);
        }
    }
}

// Instead of scss/typography/_base.scss:330
// Generate default header styles
@each $header-name, $v in $header-styles {
    #{$header-name} {
        @include header-responsive-style($v);
    }
}
```
[scss/typography/_base.scss:330](https://github.com/ncoden/foundation-sites/blob/db1e825355925eb57aaa473995b6b848957fd9cc/scss/typography/_base.scss#L330)

**3/** We could factorize the handling of `$header-styles` into two mixins. `-zf-responsive-map` is not very useful in this case because we have process each map or properties (see below), but it could be useful elsewhere.

```scss
// Generate the given map of properties
@mixin -zf-properties-map($map) {
    @each $name, $value in $map {
        #{$name}: #{$v};
    }
}

// Generate the given responsive map: write a map of properties or a single properties for each breakpoint
@mixin -zf-responsive-map($map, $property: null) {
    @each $bp, $v in $map {
        @include breakpoint($bp) {
            // the value is a map of properties
            @if typeof $v == 'map' {
                @include -zf-properties-map($v);
            }
            // the value is a property value
            @else if $property !== null {
                #{$property}: #{$v};
            }
        }
    }
}
```

**4/** For the units: we expect some defined properties to always have a particular unit. Instead of defining it _just before generating the properties_, we could simply apply _filters_ on the property or on the map of properties.
```scss
@function -zf-properties-map-filter ($properties, $filters) {
    @each $property-name, $property-value in $properties {
        @each $filter-property, $filter-func in $filters {
            @if $property-name == $filter-property {
                @if type-of($filter-func) == 'list' {
                    $func: nth($filter-func, 1);
                    $args: nth($filter-func, 2);
                    $property-value: call($func, $property-value, $args...);
                }
                @else {
                    $property-value: call($filter-func, $property-value);
                }
            }
        }
        $properties: map-merge($properties, ($property-name: $property-value));
    }
    @return $properties;
}
```

---

So all that would be used like this (instead of stuff in [scss/typography/_base.scss:330](https://github.com/ncoden/foundation-sites/blob/db1e825355925eb57aaa473995b6b848957fd9cc/scss/typography/_base.scss#L330)):
```scss
@mixin header-style ($properties) {
    $properties: -zf-properties-map-filter($properties, (
        'font-size': 'rem-calc'
        'line-height': ('unitless-calc', ('1rem')),
    ));
    @include -zf-properties-map($properties);
}
```

What do you think ? (poke @brettsmason @andycochran @kball)

_[🚀💥](https://en.wikipedia.org/wiki/Overengineering) _

**Comment by ncoden** [comment]
Pouf :boom:. Difficuly- Advenced. Because I have high expectations.

**Comment by kball** [comment]
Broadly speaking, I think this is a good direction.  I think this issue has somewhat metastasized into a few different things that maybe could be split out from each other into either multiple issues or at least possibly independent PRs

1. Separate resets from features within typography (we also need this across other parts of the framework)
2. Split out typography by component (whether this is worthwhile may depend on how much of the current flattish file is actually just reset)
3. Refactor header-styles (definitely could use it)
4. Namespace variables (We also need this globally; I'm torn if it makes sense to do all at once with migration to 7 or piecemeal/component by component as we go with a migration path)
5. Create a single "apply all of typography styles" mixin.

Does that seem right?

**Comment by ncoden** [comment]
I do not understand 5. How would it defer from the current `@mixin foundation-typography` ?

**Comment by kball** [comment]
Ah, perhaps I misunderstood your point further above:

> * There is no one single @mixin.

`foundation-typography` is fine with me if it's working for you.  by `definitely could use it` I mean that the current implementation... is a little heavy and could use refactoring into the cleaner and more functional approach you outline above.

**Comment by ncoden** [comment]
Should I make a PR with the stuff above ? I think it is a little overengeenering. But I do not see an other way to handle a map of properties. At least it is generic :)

**Comment by kball** [comment]
I think it would be useful to have a set of `functional` primitives available to work with scss maps... the _filtering_ you describe to me sounds like what I would traditionally call _mapping_ (though I admit that language is confusing when what I would think of as a _hashtable_ is called a _map_ in scss).  From that perspective, it doesn't seem like overengineering but rather introducing a useful general purpose abstraction.

**Comment by ncoden** [comment]
So, I something that can be usable like this:
```
var elem = Foundation.ElemStore(this).store
elem.delay = ...;
```

Before I realized this is almost the same thing as jQuery `$elem.data('delay', ...);`: The only difference is jQuery `.data` take HTML5 data attributes as default value.

@kball Should I rather use jQuery `.data` ? I know you planned to drop jQuery, but I don't know why.

**Comment by ncoden** [comment]
I've worked on it and the result is:
```css

h1 {
  font-size: 1.5rem;
}
@media print, screen and (min-width: 40em) {
  h1 {
    font-size: 3rem;
  }
}

h2 {
  font-size: 1.25rem;
}
@media print, screen and (min-width: 40em) {
  h2 {
    font-size: 2.5rem;
  }
}
(...)
```

I don't know how to factorize it without generating styles by breakpoint _then_ by header :sweat:
