### ISSUE TITLE
System Font stacks instead of current one 

### ISSUE THREAD

**Issue by IamManchanda** [zurb/foundation-sites#9596]
Read this article => https://www.smashingmagazine.com/2015/11/using-system-ui-fonts-practical-guide/
Some more Info => https://css-tricks.com/snippets/css/system-font-stack/

Some already implemented examples 

1. Github's website
2. Medium's website
3. Bootstrap framework
4. Wordpress CMS  
and many more 

Code i would request to change 

`$body-font-family: 'Helvetica Neue', Helvetica, Roboto, Arial, sans-serif !default;`

New code 

`$body-font-family: -apple-system, system-ui, BlinkMacSystemFont, "Segoe UI", "Roboto", "Oxygen", "Ubuntu", "Cantarell", "Fira Sans", "Helvetica Neue", Helvetica, Arial, sans-serif !default;`

If its get decided to not use linux specific ones and firefox specific system fonts then, 

`$body-font-family: -apple-system, system-ui, BlinkMacSystemFont, "Segoe UI", "Roboto", "Helvetica Neue", Helvetica, Arial, sans-serif !default;`

**Comment by ncoden** [comment]
First, I seen you opened a lot of issues these last days. Thank you a lot for your work, you help to make Foundation even better !

Concerning this issue, I agree we should at least make the font override for "Helvetica" optioned, and maybe disabled by default. But I don't know if updating `$body-font-family` would be a great idea. We are taking about low-level reset, not "styling option". In any case, we also have to disable the `font-family` Normalize set on `<html>`.

**Comment by IamManchanda** [comment]
So what do you think will be a best option ?

**Comment by ncoden** [comment]
I am not sure. I thought about something like:
```scss
$body-font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
$body-font-family-system: true;

...

$-zf-system-fonts: -apple-system, system-ui, BlinkMacSystemFont, "Segoe UI", "Roboto", "Oxygen", "Ubuntu", "Cantarell", "Fira Sans";

...

$font: $body-font-family;
@if $body-font-family-systems == true {
  $font: join($-zf-system-fonts, $font);
}
```

It allows to easily enable/disable the support for system font stacks, or to change the font family without disabled it (but this last case is not common). But maybe it is over-engineering.
