### ISSUE TITLE
Disabled buttons are hoverable

### ISSUE THREAD

**Issue by Vuurvlieg** [zurb/foundation-sites#9617]
Disabled buttons should not be hoverable right? In v6.3.0 it is, see this [example](https://jsfiddle.net/ym0m4c2u/2/)

**Comment by IamManchanda** [comment]
Yup specially success and warning !! 
https://codepen.io/IamManchanda/pen/XpmrQB

**Comment by IamManchanda** [comment]
@ncoden 

I am trying to solve this 

before 

```scss
@mixin button-disabled($color: $primary-color) {
  opacity: $button-opacity-disabled;
  cursor: not-allowed;

  &:hover, &:focus {
    background-color: $color;
    color: $button-color;
  }
}
```

and now after my code change 

```scss
@mixin button-disabled($color: $primary-color) {
  opacity: $button-opacity-disabled;
  background-color: $color;
  color: $button-color;
  cursor: not-allowed;
}

```

But the output, 

![output-disabled](https://cloud.githubusercontent.com/assets/4970624/21752089/79db7a1a-d5f8-11e6-8dce-44bdca1055ef.png)

Although this disables hover and focus functionality but also 
removes the black color from success and warning 

I think i am missing a `color-pick-contrast`, a parameter and an `@if ` statement so please help me out for the same

**What i think the best way will be to apply the default background and color for the buttons**
so how can we do that ?

**Comment by ncoden** [comment]
Look at how `@mixin button-style` is made. You want almost the same bahavior, except you do not want to apply a special style for `:hover` and `:focus`, but the default styles.

I think you have the following solutions:
- Apply all properties on the default state (like you started) and use `@function color-pick-contrast` like in `@mixin button-style`. It works with default classes because `button[disabled]` is declared after ([scss/components/_button.scss:265](https://github.com/ncoden/foundation-sites/blob/e00005c53a2ea994dd995ed050ddbe3a84f9a926/scss/components/_button.scss#L265-L266), but what if it is used on the default state (specificity 0.0.0) of a button with `:hover` and `:focus` (specificity 0.1.0) declared after ? It would not works.
- Simply generate styles by using `@mixin button-style` but with your own "disabled" values, and add the missing properties (`cursor` and `opacity`).

What do you think ?

**Comment by Vuurvlieg** [comment]
@IamManchanda Thanks for trying to solve, any update?

**Comment by IamManchanda** [comment]
@Vuurvlieg i am very sorry .... i missed these comments ..... yup will try to solve now.... heartly sorry!

**Comment by IamManchanda** [comment]
@ncoden 

I choosed first option and here is what i did to remove that [specificity issue](https://css-tricks.com/forums/topic/disable-hover-effect/)

```scss
@mixin button-disabled($color: $primary-color) {
  opacity: $button-opacity-disabled;
  cursor: not-allowed;
  background-color: $color;
  @if $color == auto {
    $color: color-pick-contrast($background, ($button-color, $button-color-alt));
  }
  &:hover, &:focus {
    box-shadow:none;
  }
}
```

It works now. Is this ohk ?
{{ Looking for your's review/approval before PR }} 

------------------------------------------------------------------------------------------------

Again i am very sorry @Vuurvlieg .... i simply missed this... my mistake
