### ISSUE TITLE
flexbox menu alignment issue

### ISSUE THREAD

**Issue by LaurelBCodin** [zurb/foundation-sites#9705]
#### How to reproduce this bug:

1. menu-centered class causes list items to stack instead of center.

#### What should happen:
list items should horizontally center

#### What happened instead:
list items stacked

#### Test case:

http://codepen.io/lbeyers/pen/vgezgK

**Comment by IamManchanda** [comment]
Yup i confirm this is a bug ( or a missing class in flexbox )
because without flexbox its working => http://codepen.io/IamManchanda/pen/BpwgoB
and with flexbox it isn't => http://codepen.io/IamManchanda/pen/MJEMyp

cc / @kball

**Comment by IamManchanda** [comment]
@LaurelBCodin : For the timebeing You can use this align center hack, **Untill i fix this**
=> http://codepen.io/IamManchanda/pen/jyGjmV

```html
<nav class="nav">
    <ul class="menu align-center">
      <li><a href="#">PORTFOLIO</a></li>
      <li><a href="#">ABOUT</a></li>
      <li><a href="#">CONTACT</a></li>
    </ul>
</nav>
```

**Comment by LaurelBCodin** [comment]
Thanks @IamManchanda!

The work around I used for it was to add this to the scss:
```
  .menu {
    justify-content: center;
  }
```

**Comment by IamManchanda** [comment]
Use this instead 

If you are using sass and autoprefixer, use this code in scss

```scss
.menu-centered > .menu {
    justify-content: center;
    align-items: flex-start; 
}
```

If you are using normal css, use this below 

```css
.menu-centered > .menu {
    -webkit-box-pack: center;
    -webkit-justify-content: center;
        -ms-flex-pack: center;
            justify-content: center;
    -webkit-box-align: start;
    -webkit-align-items: flex-start;
        -ms-flex-align: start;
            align-items: flex-start; 
}
```

------------------------------------------------------------------------------------------

Source: [Pull request](https://github.com/zurb/foundation-sites/pull/9712/files#diff-e4b53b45b19d558a4a5437c8e871f592)
