### ISSUE TITLE
[Feature] Display Classes

### ISSUE THREAD

**Issue by IamManchanda** [zurb/foundation-sites#9719]
Inspiration => https://github.com/twbs/bootstrap/blob/v4-dev/scss/utilities/_display.scss

@kball @ncoden @natewiebe13 and all others. I am talking about you!
Let me know your thoughts on this ..... as code is ready for push!!

Also, 
1. As, this have similarity to [Visibility classes](http://foundation.zurb.com/sites/docs/visibility.html), What's the take on `!important`?
2. What about responsive variations? .... Yes or No 

In short, I Wanna add these below classes 

```scss
.display-flex { /* @if $global-flexbox */ }
.display-inline-flex { /* @if $global-flexbox */ }
.display-none { }
.display-inline { }
.display-inline-block { }
.display-block {  }
.display-table { }
.display-table-cell { }
```

**Comment by natewiebe13** [comment]
My thoughts are similar to #9708. I'm just trying to think of a case where you would want to use this utility class over defining how to display the component using CSS?

**Comment by IamManchanda** [comment]
@natewiebe13 
These classes are far far different than those helper classes ... moreover it don't add much code ( generated css )

```scss
.display-none { display: none; }
.display-inline { display: inline; }
.display-inline-block { display: inline-block; }
.display-block { display: block; }
.display-table { display: table; }
.display-table-cell { display: table-cell; }
```

That's it!!!

and yes if its `$global-flexbox`, it adds these two more 

```scss
.display-flex {
  display: -webkit-box;
  display: -webkit-flex;
  display: -ms-flexbox;
  display: flex; 
}

.display-inline-flex {
  display: -webkit-inline-box;
  display: -webkit-inline-flex;
  display: -ms-inline-flexbox;
  display: inline-flex; 
}
```
