### ISSUE TITLE
[The Grid] Block Grids & Display:none

### ISSUE THREAD

**Issue by noerjeffries** [zurb/foundation-sites#9776]
#### How to reproduce this bug:

1. Set up a [Block Grid](https://foundation.zurb.com/sites/docs/grid.html#block-grids) as shown in the example [here](https://foundation.zurb.com/sites/docs/grid.html#block-grids).
2. Add a style="display:none;" attribute to the first "column" div (or a visibility class that would result in that div being hidden).
3. Notice how, when that div is hidden, its row has an empty space at the end of it.

#### What should happen:
The other columns should slide left/up to fill in the extra open space in the row.

#### What happened instead:
There is just a blank spot at the end of the row.

#### Test case:

- [CodePen: Foundation 6.3.0 Bug - Block Grids & Display:none](https://codepen.io/noerbot/pen/OWdbxz)

**Comment by IamManchanda** [comment]
Although a bug, but the way code is written in block grids , this is bound to happen

```css
.medium-up-3>.column:nth-of-type(3n+1), .medium-up-3>.columns:nth-of-type(3n+1) {
    clear: both;
}
```

**Comment by IamManchanda** [comment]
Friendly advice: Use flexbox => https://codepen.io/IamManchanda/pen/QdYJYb

http://foundation.zurb.com/sites/docs/flexbox.html

**Comment by noerjeffries** [comment]
Thanks Harman! Flexbox seems like a better solution. I'll go ahead and close this issue!

**Comment by IamManchanda** [comment]
Yup Noah .... flexbox is a better one 
because then with flexbox code becomes 

```css
.medium-up-3>.column, .medium-up-3>.columns {
    flex: 0 0 33.33333%;
    max-width: 33.33333%;
}
```
