### ISSUE TITLE
[Mixins] Font Face Mixin 

### ISSUE THREAD

**Issue by IamManchanda** [zurb/foundation-sites#9800]
I want to add a mixin called **font-face** within http://foundation.zurb.com/sites/docs/sass-mixins.html

```scss
/// Generate a font-face declaration with multiple file formats.
/// @param {String} $font-name[] - Font family name
/// @param {String} $file-name[] - File name (no extension)
/// @param {String | Number} $weight [normal] - Font weight, defaults to `normal`
/// @param {String} $style [normal] - Font style, defaults to `normal`
@mixin font-face (
  $font-name, 
  $file-name, 
  $weight: normal, 
  $style: normal
) {
  @font-face {
    font-family: quote($font-name);
    src: url($file-name + '.eot');
    src: url($file-name + '.eot?#iefix')  format('embedded-opentype'),
         url($file-name + '.woff2') format('woff2'),
         url($file-name + '.woff') format('woff'),
         url($file-name + '.ttf')  format('truetype'),
         url($file-name + '.svg##{$font-name}')  format('svg');
    font-weight: $weight;
    font-style: $style;
  }
}
```

Usage 

```scss
@include font-face('fantasy', '/fonts/fantasy');
```

cc / @brettsmason @rafibomb @kball on whether i should do a **PR** or not !
