### ISSUE TITLE
[Mixins] Background Gradient

### ISSUE THREAD

**Issue by IamManchanda** [zurb/foundation-sites#9801]
I want to add a mixin called **background-gradient** within http://foundation.zurb.com/sites/docs/sass-mixins.html

```scss
/// Background gradient helper mixin
/// @param {Color} $start-color - Start color
/// @param {Color} $end-color - End color
/// @param {String} $orientation - Type of gradient, either `vertical`, `horizontal` or `radial`
@mixin background-gradient($start-color, $end-color, $orientation) {
  background: $start-color;

  // Vertical Gradient
  @if $orientation == 'vertical' {
    background: linear-gradient(to bottom, $start-color, $end-color);
  } 
  
  // Horizontal Gradient
  @else if $orientation == 'horizontal' {
    background: linear-gradient(to right, $start-color, $end-color);
  } 
  
  // Radial Gradient
  @else if $orientation == 'radial' {
    background: radial-gradient(ellipse at center, $start-color, $end-color);
  }
}
```

Usage: 

```scss
.foo {
  @include background-gradient(green, blue, 'vertical');
}

.bar {
  @include background-gradient(green, blue, 'horizontal');
}

.baz {
  @include background-gradient(green, blue, 'radial');
}

```

cc / @brettsmason @rafibomb @kball on whether i should do a **PR** or not !

**Comment by orangedaisy** [comment]
Be more explicit with your properties. A gradient is a `background-image`, not just `background`. Likewise, the fallback color should use `background-color`.

h/t https://csswizardry.com/2016/12/css-shorthand-syntax-considered-an-anti-pattern/

**Comment by IamManchanda** [comment]
Sorry i followed this => https://www.w3schools.com/csS/css3_gradients.asp

Is this what you want @orangedaisy 

```scss
/// Background gradient helper mixin
/// @param {Color} $start-color - Start color
/// @param {Color} $end-color - End color
/// @param {String} $orientation - Type of gradient, either `vertical`, `horizontal` or `radial`
@mixin background-gradient($start-color, $end-color, $orientation) {
  background-color: $start-color;

  // Vertical Gradient
  @if $orientation == 'vertical' {
    background-image: linear-gradient(to bottom, $start-color, $end-color);
  } 
  
  // Horizontal Gradient
  @else if $orientation == 'horizontal' {
    background-image: linear-gradient(to right, $start-color, $end-color);
  } 
  
  // Radial Gradient
  @else if $orientation == 'radial' {
    background-image: radial-gradient(ellipse at center, $start-color, $end-color);
  }
}
```
