### ISSUE TITLE
Feature request "hide-if-no-js" and "show-if-no-js" visibility classes.

### ISSUE THREAD

**Issue by christianmagill** [zurb/foundation-sites#9813]
Since Foundation will remove a "no-js" class if set on the html tag, a visibility classes for hiding and showing elements based on JavaScript availability could be easily added.

This would be useful for flashes of unstyled content before Javascript is initialized.

```
html.no-js .hide-if-no-js{
  display: none !important;
}

html:not(.no-js) .show-if-no-js{
   display: none !important;
}

```

**Comment by IamManchanda** [comment]
I have to say i like it what you want, but that 2nd css, `display: block !important;` i guess!

**Comment by IamManchanda** [comment]
Here's what i feel the write way to go with it about 

```scss
.html {
  &.no-js {
    .hide-js-element {
      display: none !important;
    }
  }
  :not(.no-js) {
    .show-js-element {
      display: block !important;
    }
  }
}
```

Spl note: I purposely changed those classes name => `.hide-js-element` , `.show-js-element`
