### ISSUE TITLE
[Flexbox]Sass Mixin for flex grow/shrink - Prototyping Mixins!

### ISSUE THREAD

**Issue by IamManchanda** [zurb/foundation-sites#9814]
Inspiration => https://github.com/twbs/bootstrap/issues/21944

But hey no need for classes, just Sass Mixins will be enough btw :sweat_smile: 

Simple example, 

```scss
@include flex-grow(7);
```

**Comment by IamManchanda** [comment]
Thinked about it and i think there should be css also, but not much though ...

```scss
$flex-grow-count: 3 !default;

@mixin flex-grow ($value) {
  flex-grow: $value;
}

@mixin foundation-flex-grow {
   @for $flex-grow from 0 through $flex-grow-count {
       .flex-grow-#{$flex-grow} {
	    @include flex-grow($flex-grow);
	}
   }
}
```

This way this will only add four classes `flex-grow-0` to `flex-grow-3` 
but will also give the developer a chance to modify it to more if he needs it thanks to `$flex-grow-count`!
