### ISSUE TITLE
Clip is Deprecated

### ISSUE THREAD

**Issue by merlinpatt** [zurb/foundation-sites#9817]
According to MDN, `clip` is currently deprecated, and they recommend to use `clip-path` instead. `clip` is currently used in the `element-invisible` mixin which defines the `show-for-sr` class.

`clip`: https://developer.mozilla.org/en-US/docs/Web/CSS/clip
`clip` use in Foundation: https://github.com/zurb/foundation-sites/blob/master/scss/util/_mixins.scss#L185
`clip-path`: https://developer.mozilla.org/en-US/docs/Web/CSS/clip-path

**Comment by Deckluhm** [comment]
The MDN [`clip-path` page](https://developer.mozilla.org/en-US/docs/Web/CSS/clip-path) also states:
> **This is an experimental technology**
Because this technology's specification has not stabilized, check the compatibility table for usage in various browsers. Also note that the syntax and behavior of an experimental technology is subject to change in future versions of browsers as the specification changes.

Plus the overall [browser support](https://developer.mozilla.org/en-US/docs/Web/CSS/clip-path#Browser_compatibility) is currently extremely poor.

So even if you are right, it is probably too soon to make the switch.

**Comment by IamManchanda** [comment]
Why not use it like this for time being 

```scss
@mixin clip {  
  /* deprecated version */
  position: absolute; /* absolute or fixed positioning required */
  clip: rect(110px, 160px, 170px, 60px); /* or "auto" */
  /* values descript a top/left point and bottom/right point */

  /* current version (doesn't require positioning) */
  clip-path: inset(10px 20px 30px 40px); /* or "none" */
  /* values are from-top, from-right, from-bottom, from-left */
} 
```

Source: [CSS Tricks](https://css-tricks.com/almanac/properties/c/clip/)
