### ISSUE TITLE
6.3.1 grid breaking change flex-grid .column.row

### ISSUE THREAD

**Issue by Yimiprod** [zurb/foundation-sites#9857]
Since 6.3.1 making a columns as a row has a breaking change.
```html
<div class="row">
  <div class="is-broken columns small-8 row">
    <div class="columns small-12 medium-6"></div>
    <div class="columns small-12 medium-6"></div>
  </div>
  <div class="columns small-4></div>
</div>
```

With this example, the div `.is-broken` will have this selector match:

```css
.column.row.row, .row.row.columns {
    float: none;
    display: block;
}
```

This break the layout, making the block not acting has a flexbox anymore.
