### ISSUE TITLE
[Cards] Card Headers, Footers & Background Variants

### ISSUE THREAD

**Issue by IamManchanda** [zurb/foundation-sites#9867]
Inspiration 
- https://mdbootstrap.com/components/panels/ => **HEADER AND FOOTER**
- https://mdbootstrap.com/components/panels/ => **BACKGROUND VARIANTS**

**Required Classes** 

~~`.card-primary`, `.card-header-primary`, `.card-footer-primary` etc~~

**Update**: After some research, i think this below classes will be better

`.card.primary`, `.card-divider.primary` etc

Similar codebase to 
- http://foundation.zurb.com/sites/docs/button.html
- http://foundation.zurb.com/sites/docs/callout.html

**Comment by IamManchanda** [comment]
@DaSchTour @brettsmason 
Please let me know, on where it can be added 
Normal classes or disabled by default [Prototype utilities](https://github.com/zurb/foundation-sites/pull/9738) ??

Coz in both situation, i have the code ready to push!

```scss
@mixin card-styling(
  $color: $card-background,
  $font-color: $card-font-color,
  $font-color-alt: $card-font-color-alt
) {
  background-color: $color;
  color: color-pick-contrast($color, ($font-color, $font-color-alt));
}

@mixin foundation-card-styling {
  .card, .card-divider, .card-section {
    @each $name, $color in $foundation-palette {
      &.#{$name} {
        @include card-styling($color);
      }
    }
  }
}
```
